// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment/stripe.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Transaction          string   `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Metadata) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

type BillingDetails struct {
	Address              *BillingDetails_Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Email                string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string                  `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BillingDetails) Reset()         { *m = BillingDetails{} }
func (m *BillingDetails) String() string { return proto.CompactTextString(m) }
func (*BillingDetails) ProtoMessage()    {}
func (*BillingDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{1}
}

func (m *BillingDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillingDetails.Unmarshal(m, b)
}
func (m *BillingDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillingDetails.Marshal(b, m, deterministic)
}
func (m *BillingDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillingDetails.Merge(m, src)
}
func (m *BillingDetails) XXX_Size() int {
	return xxx_messageInfo_BillingDetails.Size(m)
}
func (m *BillingDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_BillingDetails.DiscardUnknown(m)
}

var xxx_messageInfo_BillingDetails proto.InternalMessageInfo

func (m *BillingDetails) GetAddress() *BillingDetails_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BillingDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *BillingDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BillingDetails) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type BillingDetails_Address struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Line1                string   `protobuf:"bytes,3,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2                string   `protobuf:"bytes,4,opt,name=line2,proto3" json:"line2,omitempty"`
	PostalCode           float64  `protobuf:"fixed64,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	State                string   `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BillingDetails_Address) Reset()         { *m = BillingDetails_Address{} }
func (m *BillingDetails_Address) String() string { return proto.CompactTextString(m) }
func (*BillingDetails_Address) ProtoMessage()    {}
func (*BillingDetails_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{1, 0}
}

func (m *BillingDetails_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillingDetails_Address.Unmarshal(m, b)
}
func (m *BillingDetails_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillingDetails_Address.Marshal(b, m, deterministic)
}
func (m *BillingDetails_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillingDetails_Address.Merge(m, src)
}
func (m *BillingDetails_Address) XXX_Size() int {
	return xxx_messageInfo_BillingDetails_Address.Size(m)
}
func (m *BillingDetails_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_BillingDetails_Address.DiscardUnknown(m)
}

var xxx_messageInfo_BillingDetails_Address proto.InternalMessageInfo

func (m *BillingDetails_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *BillingDetails_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *BillingDetails_Address) GetLine1() string {
	if m != nil {
		return m.Line1
	}
	return ""
}

func (m *BillingDetails_Address) GetLine2() string {
	if m != nil {
		return m.Line2
	}
	return ""
}

func (m *BillingDetails_Address) GetPostalCode() float64 {
	if m != nil {
		return m.PostalCode
	}
	return 0
}

func (m *BillingDetails_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type FraudDetails struct {
	StripeReport         string   `protobuf:"bytes,1,opt,name=stripe_report,json=stripeReport,proto3" json:"stripe_report,omitempty"`
	UserReport           string   `protobuf:"bytes,2,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FraudDetails) Reset()         { *m = FraudDetails{} }
func (m *FraudDetails) String() string { return proto.CompactTextString(m) }
func (*FraudDetails) ProtoMessage()    {}
func (*FraudDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{2}
}

func (m *FraudDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FraudDetails.Unmarshal(m, b)
}
func (m *FraudDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FraudDetails.Marshal(b, m, deterministic)
}
func (m *FraudDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FraudDetails.Merge(m, src)
}
func (m *FraudDetails) XXX_Size() int {
	return xxx_messageInfo_FraudDetails.Size(m)
}
func (m *FraudDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_FraudDetails.DiscardUnknown(m)
}

var xxx_messageInfo_FraudDetails proto.InternalMessageInfo

func (m *FraudDetails) GetStripeReport() string {
	if m != nil {
		return m.StripeReport
	}
	return ""
}

func (m *FraudDetails) GetUserReport() string {
	if m != nil {
		return m.UserReport
	}
	return ""
}

type InvoiceSettings struct {
	CustomFields         *InvoiceSettings_CustomFields `protobuf:"bytes,1,opt,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty"`
	DefaultPaymentMethod string                        `protobuf:"bytes,2,opt,name=default_payment_method,json=defaultPaymentMethod,proto3" json:"default_payment_method,omitempty"`
	Footer               string                        `protobuf:"bytes,3,opt,name=footer,proto3" json:"footer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *InvoiceSettings) Reset()         { *m = InvoiceSettings{} }
func (m *InvoiceSettings) String() string { return proto.CompactTextString(m) }
func (*InvoiceSettings) ProtoMessage()    {}
func (*InvoiceSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{3}
}

func (m *InvoiceSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceSettings.Unmarshal(m, b)
}
func (m *InvoiceSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceSettings.Marshal(b, m, deterministic)
}
func (m *InvoiceSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceSettings.Merge(m, src)
}
func (m *InvoiceSettings) XXX_Size() int {
	return xxx_messageInfo_InvoiceSettings.Size(m)
}
func (m *InvoiceSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceSettings.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceSettings proto.InternalMessageInfo

func (m *InvoiceSettings) GetCustomFields() *InvoiceSettings_CustomFields {
	if m != nil {
		return m.CustomFields
	}
	return nil
}

func (m *InvoiceSettings) GetDefaultPaymentMethod() string {
	if m != nil {
		return m.DefaultPaymentMethod
	}
	return ""
}

func (m *InvoiceSettings) GetFooter() string {
	if m != nil {
		return m.Footer
	}
	return ""
}

type InvoiceSettings_CustomFields struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceSettings_CustomFields) Reset()         { *m = InvoiceSettings_CustomFields{} }
func (m *InvoiceSettings_CustomFields) String() string { return proto.CompactTextString(m) }
func (*InvoiceSettings_CustomFields) ProtoMessage()    {}
func (*InvoiceSettings_CustomFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{3, 0}
}

func (m *InvoiceSettings_CustomFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceSettings_CustomFields.Unmarshal(m, b)
}
func (m *InvoiceSettings_CustomFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceSettings_CustomFields.Marshal(b, m, deterministic)
}
func (m *InvoiceSettings_CustomFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceSettings_CustomFields.Merge(m, src)
}
func (m *InvoiceSettings_CustomFields) XXX_Size() int {
	return xxx_messageInfo_InvoiceSettings_CustomFields.Size(m)
}
func (m *InvoiceSettings_CustomFields) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceSettings_CustomFields.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceSettings_CustomFields proto.InternalMessageInfo

func (m *InvoiceSettings_CustomFields) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InvoiceSettings_CustomFields) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Card struct {
	Brand                string                  `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Country              string                  `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	ExpMonth             float64                 `protobuf:"fixed64,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear              float64                 `protobuf:"fixed64,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	Fingerprint          string                  `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Funding              string                  `protobuf:"bytes,6,opt,name=funding,proto3" json:"funding,omitempty"`
	Last4                float64                 `protobuf:"fixed64,7,opt,name=last4,proto3" json:"last4,omitempty"`
	ThreeDSecureUsage    *Card_THREEDSecureUsage `protobuf:"bytes,8,opt,name=three_d_secure_usage,json=threeDSecureUsage,proto3" json:"three_d_secure_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{4}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Card) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Card) GetExpMonth() float64 {
	if m != nil {
		return m.ExpMonth
	}
	return 0
}

func (m *Card) GetExpYear() float64 {
	if m != nil {
		return m.ExpYear
	}
	return 0
}

func (m *Card) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *Card) GetFunding() string {
	if m != nil {
		return m.Funding
	}
	return ""
}

func (m *Card) GetLast4() float64 {
	if m != nil {
		return m.Last4
	}
	return 0
}

func (m *Card) GetThreeDSecureUsage() *Card_THREEDSecureUsage {
	if m != nil {
		return m.ThreeDSecureUsage
	}
	return nil
}

type Card_THREEDSecureUsage struct {
	Supported            bool     `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card_THREEDSecureUsage) Reset()         { *m = Card_THREEDSecureUsage{} }
func (m *Card_THREEDSecureUsage) String() string { return proto.CompactTextString(m) }
func (*Card_THREEDSecureUsage) ProtoMessage()    {}
func (*Card_THREEDSecureUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{4, 0}
}

func (m *Card_THREEDSecureUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card_THREEDSecureUsage.Unmarshal(m, b)
}
func (m *Card_THREEDSecureUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card_THREEDSecureUsage.Marshal(b, m, deterministic)
}
func (m *Card_THREEDSecureUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card_THREEDSecureUsage.Merge(m, src)
}
func (m *Card_THREEDSecureUsage) XXX_Size() int {
	return xxx_messageInfo_Card_THREEDSecureUsage.Size(m)
}
func (m *Card_THREEDSecureUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_Card_THREEDSecureUsage.DiscardUnknown(m)
}

var xxx_messageInfo_Card_THREEDSecureUsage proto.InternalMessageInfo

func (m *Card_THREEDSecureUsage) GetSupported() bool {
	if m != nil {
		return m.Supported
	}
	return false
}

type PaymentMethod struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               string          `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	BillingDetails       *BillingDetails `protobuf:"bytes,3,opt,name=billing_details,json=billingDetails,proto3" json:"billing_details,omitempty"`
	Card                 *Card           `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	Created              float64         `protobuf:"fixed64,5,opt,name=created,proto3" json:"created,omitempty"`
	Customer             string          `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	Livemode             bool            `protobuf:"varint,7,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type                 string          `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{5}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *PaymentMethod) GetBillingDetails() *BillingDetails {
	if m != nil {
		return m.BillingDetails
	}
	return nil
}

func (m *PaymentMethod) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *PaymentMethod) GetCreated() float64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PaymentMethod) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *PaymentMethod) GetLivemode() bool {
	if m != nil {
		return m.Livemode
	}
	return false
}

func (m *PaymentMethod) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PaymentMethod) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PaymentMethodDetails struct {
	Card                 *Card    `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethodDetails) Reset()         { *m = PaymentMethodDetails{} }
func (m *PaymentMethodDetails) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodDetails) ProtoMessage()    {}
func (*PaymentMethodDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{6}
}

func (m *PaymentMethodDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodDetails.Unmarshal(m, b)
}
func (m *PaymentMethodDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodDetails.Marshal(b, m, deterministic)
}
func (m *PaymentMethodDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodDetails.Merge(m, src)
}
func (m *PaymentMethodDetails) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodDetails.Size(m)
}
func (m *PaymentMethodDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodDetails.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodDetails proto.InternalMessageInfo

func (m *PaymentMethodDetails) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *PaymentMethodDetails) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Charge struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               string                `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Amount               float64               `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountRefunded       float64               `protobuf:"fixed64,4,opt,name=amount_refunded,json=amountRefunded,proto3" json:"amount_refunded,omitempty"`
	BalanceTransaction   string                `protobuf:"bytes,5,opt,name=balance_transaction,json=balanceTransaction,proto3" json:"balance_transaction,omitempty"`
	BillingDetails       *BillingDetails       `protobuf:"bytes,6,opt,name=billing_details,json=billingDetails,proto3" json:"billing_details,omitempty"`
	Captured             bool                  `protobuf:"varint,7,opt,name=captured,proto3" json:"captured,omitempty"`
	Created              float64               `protobuf:"fixed64,8,opt,name=created,proto3" json:"created,omitempty"`
	Currency             string                `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Customer             string                `protobuf:"bytes,10,opt,name=customer,proto3" json:"customer,omitempty"`
	Description          string                `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Destination          string                `protobuf:"bytes,12,opt,name=destination,proto3" json:"destination,omitempty"`
	Dispute              string                `protobuf:"bytes,13,opt,name=dispute,proto3" json:"dispute,omitempty"`
	FailureCode          string                `protobuf:"bytes,14,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage       string                `protobuf:"bytes,15,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	FraudDetails         *FraudDetails         `protobuf:"bytes,16,opt,name=fraud_details,json=fraudDetails,proto3" json:"fraud_details,omitempty"`
	Paid                 bool                  `protobuf:"varint,17,opt,name=paid,proto3" json:"paid,omitempty"`
	PaymentIntent        string                `protobuf:"bytes,18,opt,name=payment_intent,json=paymentIntent,proto3" json:"payment_intent,omitempty"`
	PaymentMethod        string                `protobuf:"bytes,19,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentMethodDetails *PaymentMethodDetails `protobuf:"bytes,20,opt,name=payment_method_details,json=paymentMethodDetails,proto3" json:"payment_method_details,omitempty"`
	ReceiptEmail         string                `protobuf:"bytes,21,opt,name=receipt_email,json=receiptEmail,proto3" json:"receipt_email,omitempty"`
	ReceiptNumber        string                `protobuf:"bytes,22,opt,name=receipt_number,json=receiptNumber,proto3" json:"receipt_number,omitempty"`
	ReceiptUrl           string                `protobuf:"bytes,23,opt,name=receipt_url,json=receiptUrl,proto3" json:"receipt_url,omitempty"`
	Review               string                `protobuf:"bytes,24,opt,name=review,proto3" json:"review,omitempty"`
	Status               string                `protobuf:"bytes,25,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Charge) Reset()         { *m = Charge{} }
func (m *Charge) String() string { return proto.CompactTextString(m) }
func (*Charge) ProtoMessage()    {}
func (*Charge) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{7}
}

func (m *Charge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Charge.Unmarshal(m, b)
}
func (m *Charge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Charge.Marshal(b, m, deterministic)
}
func (m *Charge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Charge.Merge(m, src)
}
func (m *Charge) XXX_Size() int {
	return xxx_messageInfo_Charge.Size(m)
}
func (m *Charge) XXX_DiscardUnknown() {
	xxx_messageInfo_Charge.DiscardUnknown(m)
}

var xxx_messageInfo_Charge proto.InternalMessageInfo

func (m *Charge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Charge) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Charge) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Charge) GetAmountRefunded() float64 {
	if m != nil {
		return m.AmountRefunded
	}
	return 0
}

func (m *Charge) GetBalanceTransaction() string {
	if m != nil {
		return m.BalanceTransaction
	}
	return ""
}

func (m *Charge) GetBillingDetails() *BillingDetails {
	if m != nil {
		return m.BillingDetails
	}
	return nil
}

func (m *Charge) GetCaptured() bool {
	if m != nil {
		return m.Captured
	}
	return false
}

func (m *Charge) GetCreated() float64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Charge) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Charge) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *Charge) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Charge) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Charge) GetDispute() string {
	if m != nil {
		return m.Dispute
	}
	return ""
}

func (m *Charge) GetFailureCode() string {
	if m != nil {
		return m.FailureCode
	}
	return ""
}

func (m *Charge) GetFailureMessage() string {
	if m != nil {
		return m.FailureMessage
	}
	return ""
}

func (m *Charge) GetFraudDetails() *FraudDetails {
	if m != nil {
		return m.FraudDetails
	}
	return nil
}

func (m *Charge) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *Charge) GetPaymentIntent() string {
	if m != nil {
		return m.PaymentIntent
	}
	return ""
}

func (m *Charge) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *Charge) GetPaymentMethodDetails() *PaymentMethodDetails {
	if m != nil {
		return m.PaymentMethodDetails
	}
	return nil
}

func (m *Charge) GetReceiptEmail() string {
	if m != nil {
		return m.ReceiptEmail
	}
	return ""
}

func (m *Charge) GetReceiptNumber() string {
	if m != nil {
		return m.ReceiptNumber
	}
	return ""
}

func (m *Charge) GetReceiptUrl() string {
	if m != nil {
		return m.ReceiptUrl
	}
	return ""
}

func (m *Charge) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

func (m *Charge) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Charges struct {
	Object               string    `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data                 []*Charge `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	HasMore              bool      `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	TotalCount           int64     `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Url                  string    `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Charges) Reset()         { *m = Charges{} }
func (m *Charges) String() string { return proto.CompactTextString(m) }
func (*Charges) ProtoMessage()    {}
func (*Charges) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{8}
}

func (m *Charges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Charges.Unmarshal(m, b)
}
func (m *Charges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Charges.Marshal(b, m, deterministic)
}
func (m *Charges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Charges.Merge(m, src)
}
func (m *Charges) XXX_Size() int {
	return xxx_messageInfo_Charges.Size(m)
}
func (m *Charges) XXX_DiscardUnknown() {
	xxx_messageInfo_Charges.DiscardUnknown(m)
}

var xxx_messageInfo_Charges proto.InternalMessageInfo

func (m *Charges) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Charges) GetData() []*Charge {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Charges) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *Charges) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *Charges) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type PaymentIntent struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               string                          `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Amount               float64                         `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CanceledAt           float64                         `protobuf:"fixed64,4,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	CancellationReason   string                          `protobuf:"bytes,5,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	CaptureMethod        string                          `protobuf:"bytes,6,opt,name=capture_method,json=captureMethod,proto3" json:"capture_method,omitempty"`
	Charges              *Charges                        `protobuf:"bytes,7,opt,name=charges,proto3" json:"charges,omitempty"`
	ClientSecret         string                          `protobuf:"bytes,8,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ConfirmationMethod   string                          `protobuf:"bytes,9,opt,name=confirmation_method,json=confirmationMethod,proto3" json:"confirmation_method,omitempty"`
	Created              float64                         `protobuf:"fixed64,10,opt,name=created,proto3" json:"created,omitempty"`
	Currency             string                          `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Customer             string                          `protobuf:"bytes,12,opt,name=customer,proto3" json:"customer,omitempty"`
	Description          string                          `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Invoice              string                          `protobuf:"bytes,14,opt,name=invoice,proto3" json:"invoice,omitempty"`
	LastPaymentError     *PaymentIntent_LastPaymentError `protobuf:"bytes,15,opt,name=last_payment_error,json=lastPaymentError,proto3" json:"last_payment_error,omitempty"`
	Livemode             bool                            `protobuf:"varint,16,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Metadata             *Metadata                       `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PaymentMethod        string                          `protobuf:"bytes,18,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentMethodTypes   []string                        `protobuf:"bytes,19,rep,name=payment_method_types,json=paymentMethodTypes,proto3" json:"payment_method_types,omitempty"`
	ReceiptEmail         string                          `protobuf:"bytes,20,opt,name=receipt_email,json=receiptEmail,proto3" json:"receipt_email,omitempty"`
	Review               string                          `protobuf:"bytes,21,opt,name=review,proto3" json:"review,omitempty"`
	Status               string                          `protobuf:"bytes,22,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PaymentIntent) Reset()         { *m = PaymentIntent{} }
func (m *PaymentIntent) String() string { return proto.CompactTextString(m) }
func (*PaymentIntent) ProtoMessage()    {}
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{9}
}

func (m *PaymentIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentIntent.Unmarshal(m, b)
}
func (m *PaymentIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentIntent.Marshal(b, m, deterministic)
}
func (m *PaymentIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentIntent.Merge(m, src)
}
func (m *PaymentIntent) XXX_Size() int {
	return xxx_messageInfo_PaymentIntent.Size(m)
}
func (m *PaymentIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentIntent.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentIntent proto.InternalMessageInfo

func (m *PaymentIntent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentIntent) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *PaymentIntent) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentIntent) GetCanceledAt() float64 {
	if m != nil {
		return m.CanceledAt
	}
	return 0
}

func (m *PaymentIntent) GetCancellationReason() string {
	if m != nil {
		return m.CancellationReason
	}
	return ""
}

func (m *PaymentIntent) GetCaptureMethod() string {
	if m != nil {
		return m.CaptureMethod
	}
	return ""
}

func (m *PaymentIntent) GetCharges() *Charges {
	if m != nil {
		return m.Charges
	}
	return nil
}

func (m *PaymentIntent) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *PaymentIntent) GetConfirmationMethod() string {
	if m != nil {
		return m.ConfirmationMethod
	}
	return ""
}

func (m *PaymentIntent) GetCreated() float64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PaymentIntent) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PaymentIntent) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *PaymentIntent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PaymentIntent) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

func (m *PaymentIntent) GetLastPaymentError() *PaymentIntent_LastPaymentError {
	if m != nil {
		return m.LastPaymentError
	}
	return nil
}

func (m *PaymentIntent) GetLivemode() bool {
	if m != nil {
		return m.Livemode
	}
	return false
}

func (m *PaymentIntent) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PaymentIntent) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *PaymentIntent) GetPaymentMethodTypes() []string {
	if m != nil {
		return m.PaymentMethodTypes
	}
	return nil
}

func (m *PaymentIntent) GetReceiptEmail() string {
	if m != nil {
		return m.ReceiptEmail
	}
	return ""
}

func (m *PaymentIntent) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

func (m *PaymentIntent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PaymentIntent_LastPaymentError struct {
	Charge               string         `protobuf:"bytes,1,opt,name=charge,proto3" json:"charge,omitempty"`
	Code                 string         `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	DocUrl               string         `protobuf:"bytes,3,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	Message              string         `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Type                 string         `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Param                string         `protobuf:"bytes,6,opt,name=param,proto3" json:"param,omitempty"`
	PaymentMethod        *PaymentMethod `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PaymentIntent_LastPaymentError) Reset()         { *m = PaymentIntent_LastPaymentError{} }
func (m *PaymentIntent_LastPaymentError) String() string { return proto.CompactTextString(m) }
func (*PaymentIntent_LastPaymentError) ProtoMessage()    {}
func (*PaymentIntent_LastPaymentError) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{9, 0}
}

func (m *PaymentIntent_LastPaymentError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentIntent_LastPaymentError.Unmarshal(m, b)
}
func (m *PaymentIntent_LastPaymentError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentIntent_LastPaymentError.Marshal(b, m, deterministic)
}
func (m *PaymentIntent_LastPaymentError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentIntent_LastPaymentError.Merge(m, src)
}
func (m *PaymentIntent_LastPaymentError) XXX_Size() int {
	return xxx_messageInfo_PaymentIntent_LastPaymentError.Size(m)
}
func (m *PaymentIntent_LastPaymentError) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentIntent_LastPaymentError.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentIntent_LastPaymentError proto.InternalMessageInfo

func (m *PaymentIntent_LastPaymentError) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *PaymentIntent_LastPaymentError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PaymentIntent_LastPaymentError) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *PaymentIntent_LastPaymentError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PaymentIntent_LastPaymentError) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PaymentIntent_LastPaymentError) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *PaymentIntent_LastPaymentError) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

type SetupIntent struct {
	Id                   string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               string                      `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	CancellationReason   string                      `protobuf:"bytes,3,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	ClientSecret         string                      `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Created              float64                     `protobuf:"fixed64,5,opt,name=created,proto3" json:"created,omitempty"`
	Customer             string                      `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	Description          string                      `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	LastSetupError       *SetupIntent_LastSetupError `protobuf:"bytes,8,opt,name=last_setup_error,json=lastSetupError,proto3" json:"last_setup_error,omitempty"`
	Livemode             bool                        `protobuf:"varint,9,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Metadata             *Metadata                   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PaymentMethod        string                      `protobuf:"bytes,11,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentMethodTypes   []string                    `protobuf:"bytes,12,rep,name=payment_method_types,json=paymentMethodTypes,proto3" json:"payment_method_types,omitempty"`
	Status               string                      `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	Usage                string                      `protobuf:"bytes,14,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SetupIntent) Reset()         { *m = SetupIntent{} }
func (m *SetupIntent) String() string { return proto.CompactTextString(m) }
func (*SetupIntent) ProtoMessage()    {}
func (*SetupIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{10}
}

func (m *SetupIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupIntent.Unmarshal(m, b)
}
func (m *SetupIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupIntent.Marshal(b, m, deterministic)
}
func (m *SetupIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupIntent.Merge(m, src)
}
func (m *SetupIntent) XXX_Size() int {
	return xxx_messageInfo_SetupIntent.Size(m)
}
func (m *SetupIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupIntent.DiscardUnknown(m)
}

var xxx_messageInfo_SetupIntent proto.InternalMessageInfo

func (m *SetupIntent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetupIntent) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *SetupIntent) GetCancellationReason() string {
	if m != nil {
		return m.CancellationReason
	}
	return ""
}

func (m *SetupIntent) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *SetupIntent) GetCreated() float64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SetupIntent) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *SetupIntent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SetupIntent) GetLastSetupError() *SetupIntent_LastSetupError {
	if m != nil {
		return m.LastSetupError
	}
	return nil
}

func (m *SetupIntent) GetLivemode() bool {
	if m != nil {
		return m.Livemode
	}
	return false
}

func (m *SetupIntent) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SetupIntent) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *SetupIntent) GetPaymentMethodTypes() []string {
	if m != nil {
		return m.PaymentMethodTypes
	}
	return nil
}

func (m *SetupIntent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SetupIntent) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

type SetupIntent_LastSetupError struct {
	Code                 string         `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DeclineCode          string         `protobuf:"bytes,2,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	DocUrl               string         `protobuf:"bytes,3,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	Message              string         `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Param                string         `protobuf:"bytes,5,opt,name=param,proto3" json:"param,omitempty"`
	PaymentMethod        *PaymentMethod `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Type                 string         `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetupIntent_LastSetupError) Reset()         { *m = SetupIntent_LastSetupError{} }
func (m *SetupIntent_LastSetupError) String() string { return proto.CompactTextString(m) }
func (*SetupIntent_LastSetupError) ProtoMessage()    {}
func (*SetupIntent_LastSetupError) Descriptor() ([]byte, []int) {
	return fileDescriptor_1666949cdfd0f885, []int{10, 0}
}

func (m *SetupIntent_LastSetupError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupIntent_LastSetupError.Unmarshal(m, b)
}
func (m *SetupIntent_LastSetupError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupIntent_LastSetupError.Marshal(b, m, deterministic)
}
func (m *SetupIntent_LastSetupError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupIntent_LastSetupError.Merge(m, src)
}
func (m *SetupIntent_LastSetupError) XXX_Size() int {
	return xxx_messageInfo_SetupIntent_LastSetupError.Size(m)
}
func (m *SetupIntent_LastSetupError) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupIntent_LastSetupError.DiscardUnknown(m)
}

var xxx_messageInfo_SetupIntent_LastSetupError proto.InternalMessageInfo

func (m *SetupIntent_LastSetupError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SetupIntent_LastSetupError) GetDeclineCode() string {
	if m != nil {
		return m.DeclineCode
	}
	return ""
}

func (m *SetupIntent_LastSetupError) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *SetupIntent_LastSetupError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SetupIntent_LastSetupError) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *SetupIntent_LastSetupError) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *SetupIntent_LastSetupError) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*Metadata)(nil), "api.payment.Metadata")
	proto.RegisterType((*BillingDetails)(nil), "api.payment.BillingDetails")
	proto.RegisterType((*BillingDetails_Address)(nil), "api.payment.BillingDetails.Address")
	proto.RegisterType((*FraudDetails)(nil), "api.payment.FraudDetails")
	proto.RegisterType((*InvoiceSettings)(nil), "api.payment.InvoiceSettings")
	proto.RegisterType((*InvoiceSettings_CustomFields)(nil), "api.payment.InvoiceSettings.CustomFields")
	proto.RegisterType((*Card)(nil), "api.payment.Card")
	proto.RegisterType((*Card_THREEDSecureUsage)(nil), "api.payment.Card.THREEDSecureUsage")
	proto.RegisterType((*PaymentMethod)(nil), "api.payment.PaymentMethod")
	proto.RegisterType((*PaymentMethodDetails)(nil), "api.payment.PaymentMethodDetails")
	proto.RegisterType((*Charge)(nil), "api.payment.Charge")
	proto.RegisterType((*Charges)(nil), "api.payment.Charges")
	proto.RegisterType((*PaymentIntent)(nil), "api.payment.PaymentIntent")
	proto.RegisterType((*PaymentIntent_LastPaymentError)(nil), "api.payment.PaymentIntent.LastPaymentError")
	proto.RegisterType((*SetupIntent)(nil), "api.payment.SetupIntent")
	proto.RegisterType((*SetupIntent_LastSetupError)(nil), "api.payment.SetupIntent.LastSetupError")
}

func init() { proto.RegisterFile("payment/stripe.proto", fileDescriptor_1666949cdfd0f885) }

var fileDescriptor_1666949cdfd0f885 = []byte{
	// 1538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdf, 0x6e, 0xdb, 0xb6,
	0x17, 0x86, 0x9d, 0x3f, 0xb2, 0x8f, 0x6c, 0x27, 0x61, 0xdc, 0x54, 0x4d, 0x7f, 0x40, 0x53, 0x17,
	0x45, 0xfa, 0xc3, 0x00, 0x77, 0xcd, 0x7a, 0xb1, 0x9b, 0x0d, 0x6b, 0xd3, 0x14, 0x2b, 0xb0, 0x14,
	0xab, 0x92, 0x62, 0xe8, 0x6e, 0x04, 0x46, 0x3a, 0x4e, 0x34, 0xc8, 0x92, 0x40, 0x51, 0x59, 0xf3,
	0x20, 0x03, 0x8a, 0x3d, 0xc3, 0x5e, 0x61, 0x0f, 0xb0, 0x97, 0xd8, 0xed, 0xb0, 0x17, 0xd8, 0xf5,
	0xc0, 0x43, 0x52, 0x91, 0x62, 0xc7, 0x68, 0xba, 0x3b, 0x9e, 0xc3, 0x43, 0xf3, 0xf0, 0x9c, 0xef,
	0xfb, 0x48, 0x19, 0x86, 0x39, 0xbf, 0x98, 0x62, 0x2a, 0x1f, 0x17, 0x52, 0xc4, 0x39, 0x8e, 0x73,
	0x91, 0xc9, 0x8c, 0xb9, 0x3c, 0x8f, 0xc7, 0x66, 0x66, 0xf4, 0x0d, 0x74, 0x0e, 0x51, 0xf2, 0x88,
	0x4b, 0xce, 0x18, 0x2c, 0x97, 0x05, 0x0a, 0xaf, 0xb5, 0xd3, 0x7a, 0xd4, 0xf5, 0x69, 0xcc, 0x76,
	0xc0, 0x95, 0x82, 0xa7, 0x05, 0x0f, 0x65, 0x9c, 0xa5, 0x5e, 0x9b, 0xa6, 0xea, 0xae, 0xd1, 0x6f,
	0x6d, 0x18, 0x3c, 0x8f, 0x93, 0x24, 0x4e, 0x4f, 0x5f, 0xa0, 0xe4, 0x71, 0x52, 0xb0, 0xaf, 0xc0,
	0xe1, 0x51, 0x24, 0xb0, 0x28, 0xe8, 0xb7, 0xdc, 0xbd, 0x07, 0xe3, 0xda, 0x9e, 0xe3, 0x66, 0xf4,
	0xf8, 0x99, 0x0e, 0xf5, 0xed, 0x1a, 0x36, 0x84, 0x15, 0x9c, 0xf2, 0x38, 0x31, 0xbb, 0x69, 0x43,
	0x65, 0x97, 0xf2, 0x29, 0x7a, 0x4b, 0x3a, 0x3b, 0x35, 0x56, 0x91, 0xf9, 0x59, 0x96, 0xa2, 0xb7,
	0xac, 0x23, 0xc9, 0xd8, 0xfe, 0xb5, 0x05, 0x8e, 0xf9, 0x51, 0xb5, 0x2a, 0x8c, 0xe5, 0x85, 0x3d,
	0x93, 0x1a, 0x33, 0x0f, 0x9c, 0x30, 0x2b, 0x53, 0x29, 0x2e, 0xcc, 0x0e, 0xd6, 0x54, 0xbf, 0x97,
	0xc4, 0x29, 0x3e, 0x31, 0x9b, 0x68, 0xc3, 0x7a, 0xf7, 0xec, 0x2e, 0x64, 0xb0, 0x7b, 0xe0, 0xe6,
	0x59, 0x21, 0x79, 0x12, 0x84, 0x59, 0x84, 0xde, 0xca, 0x4e, 0xeb, 0x51, 0xcb, 0x07, 0xed, 0xda,
	0xcf, 0x22, 0x4a, 0xae, 0x90, 0x5c, 0xa2, 0xb7, 0xaa, 0x97, 0x91, 0x31, 0x3a, 0x86, 0xde, 0x4b,
	0xc1, 0xcb, 0xc8, 0xd6, 0xea, 0x01, 0xf4, 0x75, 0x77, 0x02, 0x81, 0x79, 0x26, 0xa4, 0xc9, 0xb4,
	0xa7, 0x9d, 0x3e, 0xf9, 0xd4, 0x5e, 0xaa, 0x1b, 0x36, 0x44, 0x67, 0x0d, 0xca, 0xa5, 0x03, 0x46,
	0x7f, 0xb7, 0x60, 0xed, 0x55, 0x7a, 0x9e, 0xc5, 0x21, 0x1e, 0xa1, 0x94, 0x71, 0x7a, 0x5a, 0xb0,
	0xd7, 0xd0, 0x0f, 0xcb, 0x42, 0x66, 0xd3, 0x60, 0x12, 0x63, 0x12, 0xd9, 0x5e, 0xfc, 0xbf, 0xd1,
	0x8b, 0x2b, 0x8b, 0xc6, 0xfb, 0xb4, 0xe2, 0x25, 0x2d, 0xf0, 0x7b, 0x61, 0xcd, 0x62, 0x4f, 0x61,
	0x2b, 0xc2, 0x09, 0x2f, 0x13, 0x19, 0x98, 0xd5, 0xc1, 0x14, 0xe5, 0x59, 0x16, 0x99, 0x7c, 0x86,
	0x66, 0xf6, 0x7b, 0x3d, 0x79, 0x48, 0x73, 0x6c, 0x0b, 0x56, 0x27, 0x59, 0x26, 0x51, 0x98, 0x9a,
	0x1a, 0x6b, 0xfb, 0x4b, 0xe8, 0xd5, 0xf7, 0xaa, 0xda, 0xdb, 0x6a, 0xb6, 0xf7, 0x9c, 0x27, 0x25,
	0x5a, 0x20, 0x90, 0x31, 0xfa, 0xa3, 0x0d, 0xcb, 0xfb, 0x5c, 0x44, 0x6a, 0xfa, 0x44, 0xf0, 0x34,
	0x32, 0x6b, 0xb4, 0xb1, 0xa0, 0xbb, 0x77, 0xa1, 0x8b, 0xef, 0xf3, 0x60, 0x9a, 0xa5, 0xf2, 0x8c,
	0xb2, 0x69, 0xf9, 0x1d, 0x7c, 0x9f, 0x1f, 0x2a, 0x9b, 0xdd, 0x01, 0x35, 0x0e, 0x2e, 0x90, 0x0b,
	0xea, 0x73, 0xcb, 0x77, 0xf0, 0x7d, 0xfe, 0x0e, 0x39, 0x71, 0x60, 0x12, 0xa7, 0xa7, 0x28, 0x72,
	0x11, 0xa7, 0x92, 0x3a, 0xdd, 0xf5, 0xeb, 0x2e, 0xb5, 0xe7, 0xa4, 0x4c, 0xa3, 0x38, 0x3d, 0x35,
	0xcd, 0xb6, 0x26, 0x61, 0x87, 0x17, 0xf2, 0xa9, 0xe7, 0xd0, 0x6f, 0x6a, 0x83, 0x1d, 0xc3, 0x50,
	0x9e, 0x09, 0xc4, 0x20, 0x0a, 0x0a, 0x0c, 0x4b, 0x81, 0x41, 0x59, 0xf0, 0x53, 0xf4, 0x3a, 0x73,
	0xd8, 0xa2, 0x8e, 0x3a, 0x3e, 0xfe, 0xd6, 0x3f, 0x38, 0x78, 0x71, 0x44, 0xb1, 0x6f, 0x55, 0xa8,
	0xbf, 0x41, 0x3f, 0x50, 0x77, 0x6d, 0x3f, 0x81, 0x8d, 0x99, 0x38, 0xf6, 0x3f, 0xe8, 0x16, 0x65,
	0xae, 0x40, 0x82, 0xba, 0x50, 0x1d, 0xff, 0xd2, 0x31, 0xfa, 0xbd, 0x0d, 0xfd, 0x66, 0xbf, 0x06,
	0xd0, 0x8e, 0x6d, 0x45, 0xdb, 0x31, 0xf5, 0x2f, 0x3b, 0xf9, 0x09, 0x43, 0x8b, 0x3a, 0x63, 0xb1,
	0x17, 0xb0, 0x76, 0xa2, 0x79, 0x1c, 0x44, 0x1a, 0xca, 0x54, 0x52, 0x77, 0xef, 0xee, 0x02, 0xae,
	0xfb, 0x83, 0x93, 0xa6, 0x52, 0x3c, 0x84, 0xe5, 0x90, 0x8b, 0x88, 0x2a, 0xee, 0xee, 0x6d, 0xcc,
	0x1c, 0xdc, 0xa7, 0x69, 0xea, 0xa9, 0x40, 0xae, 0x8e, 0xa0, 0x79, 0x66, 0x4d, 0xb6, 0x0d, 0x1d,
	0x0d, 0x52, 0x14, 0xa6, 0xf4, 0x95, 0xad, 0xe6, 0x92, 0xf8, 0x1c, 0xa7, 0x8a, 0x9e, 0x0e, 0x9d,
	0xbc, 0xb2, 0xd9, 0x13, 0xe8, 0x4c, 0x8d, 0xee, 0x99, 0xaa, 0xdf, 0x6a, 0x6c, 0x6e, 0x45, 0xd1,
	0xaf, 0xc2, 0x14, 0x42, 0xe5, 0x45, 0x8e, 0x5e, 0x57, 0x23, 0x54, 0x8d, 0x47, 0x6f, 0x60, 0xd8,
	0x28, 0xdf, 0xd5, 0x73, 0xb5, 0x16, 0x9f, 0xcb, 0xfe, 0x64, 0xbb, 0xf6, 0x93, 0x1f, 0x1c, 0x58,
	0xdd, 0x3f, 0xe3, 0xe2, 0x14, 0x3f, 0xba, 0x17, 0x5b, 0xb0, 0xca, 0xa7, 0x0a, 0xe4, 0x06, 0xd5,
	0xc6, 0x62, 0xbb, 0xb0, 0xa6, 0x47, 0x81, 0x40, 0x05, 0x48, 0x8c, 0x0c, 0xb4, 0x07, 0xda, 0xed,
	0x1b, 0x2f, 0x7b, 0x0c, 0x9b, 0x27, 0x3c, 0xe1, 0x69, 0x88, 0x41, 0x5d, 0xed, 0x35, 0xd2, 0x99,
	0x99, 0x3a, 0xbe, 0x9c, 0x99, 0xd7, 0xfd, 0xd5, 0x9b, 0x77, 0x5f, 0x35, 0x8f, 0xe7, 0xb2, 0x14,
	0x18, 0xd9, 0x06, 0x59, 0xbb, 0xde, 0xf2, 0xce, 0x9c, 0x96, 0x0b, 0x81, 0x69, 0x78, 0x61, 0x7a,
	0x51, 0xd9, 0x0d, 0x38, 0xc0, 0x15, 0x38, 0xec, 0x80, 0x1b, 0x61, 0x11, 0x8a, 0x38, 0xa7, 0xc3,
	0xb9, 0x9a, 0xc6, 0x35, 0x97, 0x89, 0x90, 0x71, 0xca, 0x29, 0xa2, 0x57, 0x45, 0x58, 0x97, 0xca,
	0x2a, 0x8a, 0x8b, 0xbc, 0x94, 0xe8, 0xf5, 0x35, 0xd1, 0x8d, 0xc9, 0xee, 0x43, 0x6f, 0xc2, 0xe3,
	0x44, 0x71, 0x99, 0xee, 0x83, 0x81, 0x51, 0x09, 0xed, 0xa3, 0x0b, 0x61, 0x17, 0xd6, 0x6c, 0xc8,
	0x14, 0x0b, 0x22, 0xfc, 0x1a, 0x45, 0x0d, 0x8c, 0xfb, 0x50, 0x7b, 0xd9, 0xd7, 0xd0, 0x9f, 0xa8,
	0x3b, 0xa2, 0xaa, 0xed, 0x3a, 0xd5, 0xf6, 0x4e, 0xa3, 0xb6, 0xf5, 0x5b, 0xc4, 0xef, 0x4d, 0xea,
	0x77, 0x0a, 0x83, 0xe5, 0x9c, 0xc7, 0x91, 0xb7, 0x41, 0x35, 0xa5, 0x31, 0x7b, 0x08, 0x03, 0xab,
	0xda, 0x71, 0x2a, 0x31, 0x95, 0x1e, 0xa3, 0xbd, 0xfb, 0xc6, 0xfb, 0x8a, 0x9c, 0xf5, 0x30, 0x23,
	0xee, 0x9b, 0x8d, 0x30, 0xa3, 0x12, 0x3f, 0xc0, 0x56, 0x33, 0xac, 0x4a, 0x75, 0x48, 0xa9, 0xde,
	0x6f, 0xa4, 0x3a, 0x8f, 0x22, 0xfe, 0x30, 0x9f, 0x47, 0x9c, 0x07, 0xd0, 0x17, 0x18, 0x62, 0x9c,
	0xcb, 0x40, 0xbf, 0x01, 0x6e, 0xe9, 0xeb, 0xd0, 0x38, 0x0f, 0xe8, 0x29, 0xf0, 0x10, 0x06, 0x36,
	0x28, 0x2d, 0xa7, 0x27, 0x28, 0xbc, 0x2d, 0x9d, 0xa4, 0xf1, 0xbe, 0x26, 0xa7, 0xba, 0x35, 0x6d,
	0x58, 0x29, 0x12, 0xef, 0xb6, 0xbe, 0x35, 0x8d, 0xeb, 0xad, 0x48, 0x14, 0x6f, 0x04, 0x9e, 0xc7,
	0xf8, 0xb3, 0xe7, 0x69, 0x3e, 0x69, 0x4b, 0xf9, 0xd5, 0x65, 0x5d, 0x16, 0xde, 0x1d, 0xed, 0xd7,
	0xd6, 0xe8, 0x43, 0x0b, 0x1c, 0x4d, 0xcd, 0xa2, 0xc6, 0xc5, 0x56, 0x83, 0x8b, 0xbb, 0xb0, 0x4c,
	0xa2, 0xd2, 0xde, 0x59, 0x7a, 0xe4, 0xee, 0x6d, 0x36, 0x99, 0x4f, 0x6b, 0x7d, 0x0a, 0x50, 0x17,
	0xce, 0x19, 0x2f, 0x82, 0x69, 0x26, 0xf4, 0x9b, 0xa6, 0xe3, 0x3b, 0x67, 0xbc, 0x38, 0xcc, 0x04,
	0xaa, 0xc4, 0x65, 0xa6, 0x5f, 0x16, 0x8a, 0xd4, 0x8a, 0xb3, 0x4b, 0x3e, 0x90, 0x6b, 0x9f, 0x88,
	0xbd, 0x0e, 0x4b, 0xea, 0x44, 0x5a, 0xf0, 0xd4, 0x70, 0xf4, 0x4b, 0xa7, 0x12, 0x72, 0xd3, 0xc9,
	0xff, 0x2a, 0x1e, 0xf7, 0xc0, 0x0d, 0x15, 0xed, 0x13, 0x8c, 0x02, 0x2e, 0x8d, 0x70, 0x80, 0x75,
	0x3d, 0x93, 0x4a, 0x34, 0xb4, 0x95, 0x10, 0x37, 0x02, 0x81, 0xbc, 0xb8, 0x14, 0x8d, 0xfa, 0x94,
	0x4f, 0x33, 0xaa, 0x6d, 0x86, 0xde, 0x16, 0x5b, 0xfa, 0x00, 0x7d, 0xe3, 0x35, 0xd8, 0x1a, 0x83,
	0x13, 0xea, 0x22, 0x93, 0x28, 0xb8, 0x7b, 0xc3, 0x39, 0x45, 0x2c, 0x7c, 0x1b, 0xa4, 0x20, 0x13,
	0x26, 0xb1, 0x82, 0x62, 0x81, 0xa1, 0x40, 0x49, 0x7a, 0xd1, 0xf5, 0x7b, 0xda, 0x79, 0x44, 0x3e,
	0x4a, 0x36, 0x4b, 0x27, 0xb1, 0x98, 0xea, 0x64, 0x4d, 0x02, 0x5d, 0x93, 0x6c, 0x6d, 0xca, 0x64,
	0x51, 0xd3, 0x1f, 0xb8, 0x5e, 0x7f, 0xdc, 0x05, 0xfa, 0xd3, 0x5b, 0xac, 0x3f, 0xfd, 0x59, 0xfd,
	0xf1, 0xc0, 0x89, 0xf5, 0x7b, 0xcc, 0xc8, 0x87, 0x35, 0xd9, 0x3b, 0x60, 0xea, 0xe5, 0x50, 0x3d,
	0xbc, 0x50, 0x88, 0x4c, 0x90, 0x7a, 0xb8, 0x7b, 0x9f, 0xcd, 0xe3, 0x9a, 0x06, 0xc1, 0xf8, 0x3b,
	0x5e, 0xd8, 0xf7, 0xd8, 0x81, 0x5a, 0xe2, 0xaf, 0x27, 0x57, 0x3c, 0x8d, 0x5b, 0x72, 0x7d, 0xc1,
	0x2d, 0xb9, 0xf1, 0x71, 0xb7, 0xe4, 0xac, 0x80, 0xb0, 0x79, 0x02, 0xf2, 0x79, 0xf5, 0x71, 0x62,
	0x05, 0x44, 0x5d, 0x7e, 0x85, 0xb7, 0xb9, 0xb3, 0xa4, 0x1a, 0xd2, 0x08, 0x3e, 0x56, 0x33, 0xb3,
	0xca, 0x30, 0x9c, 0xa3, 0x0c, 0x97, 0x8c, 0xbe, 0x75, 0x0d, 0xa3, 0xb7, 0xea, 0x8c, 0xde, 0xfe,
	0xb3, 0x05, 0xeb, 0x57, 0x6b, 0xa4, 0x82, 0x35, 0xb6, 0x2c, 0xb5, 0xb5, 0x45, 0xdf, 0x12, 0xaa,
	0x4a, 0xe6, 0xb6, 0x56, 0x63, 0x76, 0x1b, 0x9c, 0x28, 0x0b, 0x49, 0x5f, 0xcc, 0xfb, 0x36, 0xca,
	0x42, 0xa5, 0x2d, 0x1e, 0x38, 0x56, 0xe4, 0xf5, 0x67, 0x83, 0x35, 0xab, 0x4b, 0x7f, 0xe5, 0xf2,
	0xd2, 0xa7, 0x0f, 0x19, 0x2e, 0xf8, 0xd4, 0x7e, 0x2b, 0x90, 0xc1, 0x9e, 0xcd, 0xd4, 0x52, 0x13,
	0x62, 0xfb, 0x7a, 0x75, 0xbd, 0x52, 0xe7, 0xd1, 0x3f, 0x2b, 0xe0, 0x1e, 0xa1, 0x2c, 0xf3, 0x1b,
	0xaa, 0xc2, 0x35, 0xe4, 0x5e, 0xba, 0x96, 0xdc, 0x33, 0x2c, 0x5c, 0x9e, 0xc3, 0xc2, 0x4f, 0x7b,
	0xc7, 0x5d, 0x21, 0x8e, 0x33, 0x4b, 0x9c, 0x37, 0x40, 0xb8, 0x0e, 0x0a, 0x75, 0x52, 0x43, 0x0e,
	0xfd, 0xaa, 0xdb, 0x6d, 0x94, 0xaa, 0x56, 0x09, 0xa2, 0x06, 0xd9, 0x9a, 0x18, 0x83, 0xa4, 0x61,
	0x37, 0x68, 0xd1, 0x5d, 0x40, 0x0b, 0xf8, 0x54, 0x5a, 0xb8, 0x37, 0xa1, 0x45, 0xef, 0x5a, 0x5a,
	0x5c, 0x22, 0xbb, 0x5f, 0x47, 0xb6, 0x42, 0x94, 0xfe, 0xa6, 0xd0, 0x4a, 0xa2, 0x8d, 0xed, 0xbf,
	0x5a, 0x30, 0x68, 0x1e, 0xbc, 0x42, 0x75, 0xab, 0x86, 0xea, 0xfb, 0xd0, 0x8b, 0x30, 0x54, 0xdf,
	0xb9, 0x41, 0x0d, 0xf1, 0xae, 0xf1, 0xed, 0x7f, 0x22, 0xf0, 0x2b, 0x90, 0xaf, 0x2c, 0x06, 0xf9,
	0xea, 0x0d, 0x41, 0x5e, 0x31, 0xca, 0xb9, 0x64, 0xd4, 0xf3, 0xee, 0x8f, 0x8e, 0x09, 0x3a, 0x59,
	0xa5, 0xff, 0x3d, 0xbe, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xd1, 0x74, 0xb6, 0x0f, 0x11,
	0x00, 0x00,
}
