FROM golang:1.13-alpine

WORKDIR /gateway
COPY go.mod . 
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

# For some reason .dockerignore doesn't work.
COPY cmd ./cmd
COPY internal ./internal
COPY protogen ./protogen
COPY .env .

CMD ["go", "run", "cmd/main.go"]
