FROM golang:1.16-alpine

WORKDIR /gateway
COPY go.mod . 
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

COPY . .

CMD ["go", "run", "cmd/main.go"]