apiVersion: skaffold/v1
kind: Config
metadata:
  name: gateway-go
build:
  artifacts:
  - image: registry.gitlab.com/isaiahwong/go/api/gateway
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - k8s/gateway.yaml
    # - manifest/ingress.yaml
