apiVersion: v1
kind: Service
metadata:
  name: redis-gateway-service
spec:
  selector:
    name: redis-gateway
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-gateway
  labels:
    name: redis-gateway
spec:
  hostname: redis-gateway
  subdomain: redis-gateway-service
  containers:
    - name: redis
      image: redis
      command:
        - redis-server
        - '/redis-master/redis.conf'
      env:
        - name: MASTER
          value: 'true'
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: 60m
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-gateway-config
        items:
          - key: redis-config
            path: redis.conf
