// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/v1/accounts.proto

package accounts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Body struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HydraResponse struct {
	Challenge            string   `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	RequestUrl           string   `protobuf:"bytes,2,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Skip                 bool     `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	RedirectTo           string   `protobuf:"bytes,6,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HydraResponse) Reset()         { *m = HydraResponse{} }
func (m *HydraResponse) String() string { return proto.CompactTextString(m) }
func (*HydraResponse) ProtoMessage()    {}
func (*HydraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{2}
}

func (m *HydraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HydraResponse.Unmarshal(m, b)
}
func (m *HydraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HydraResponse.Marshal(b, m, deterministic)
}
func (m *HydraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HydraResponse.Merge(m, src)
}
func (m *HydraResponse) XXX_Size() int {
	return xxx_messageInfo_HydraResponse.Size(m)
}
func (m *HydraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HydraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HydraResponse proto.InternalMessageInfo

func (m *HydraResponse) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *HydraResponse) GetRequestUrl() string {
	if m != nil {
		return m.RequestUrl
	}
	return ""
}

func (m *HydraResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *HydraResponse) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

func (m *HydraResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *HydraResponse) GetRedirectTo() string {
	if m != nil {
		return m.RedirectTo
	}
	return ""
}

type IntrospectRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntrospectRequest) Reset()         { *m = IntrospectRequest{} }
func (m *IntrospectRequest) String() string { return proto.CompactTextString(m) }
func (*IntrospectRequest) ProtoMessage()    {}
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{3}
}

func (m *IntrospectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntrospectRequest.Unmarshal(m, b)
}
func (m *IntrospectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntrospectRequest.Marshal(b, m, deterministic)
}
func (m *IntrospectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntrospectRequest.Merge(m, src)
}
func (m *IntrospectRequest) XXX_Size() int {
	return xxx_messageInfo_IntrospectRequest.Size(m)
}
func (m *IntrospectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntrospectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntrospectRequest proto.InternalMessageInfo

func (m *IntrospectRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IntrospectRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type IntrospectResponse struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Aud                  []string `protobuf:"bytes,2,rep,name=aud,proto3" json:"aud,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Exp                  int64    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Ext                  []byte   `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
	Iat                  int64    `protobuf:"varint,6,opt,name=iat,proto3" json:"iat,omitempty"`
	Iss                  string   `protobuf:"bytes,7,opt,name=iss,proto3" json:"iss,omitempty"`
	Nbf                  int64    `protobuf:"varint,8,opt,name=nbf,proto3" json:"nbf,omitempty"`
	ObfuscatedSubject    string   `protobuf:"bytes,9,opt,name=obfuscated_subject,json=obfuscatedSubject,proto3" json:"obfuscated_subject,omitempty"`
	Scope                string   `protobuf:"bytes,10,opt,name=scope,proto3" json:"scope,omitempty"`
	Sub                  string   `protobuf:"bytes,11,opt,name=sub,proto3" json:"sub,omitempty"`
	TokenType            string   `protobuf:"bytes,12,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Username             string   `protobuf:"bytes,13,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntrospectResponse) Reset()         { *m = IntrospectResponse{} }
func (m *IntrospectResponse) String() string { return proto.CompactTextString(m) }
func (*IntrospectResponse) ProtoMessage()    {}
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{4}
}

func (m *IntrospectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntrospectResponse.Unmarshal(m, b)
}
func (m *IntrospectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntrospectResponse.Marshal(b, m, deterministic)
}
func (m *IntrospectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntrospectResponse.Merge(m, src)
}
func (m *IntrospectResponse) XXX_Size() int {
	return xxx_messageInfo_IntrospectResponse.Size(m)
}
func (m *IntrospectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IntrospectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IntrospectResponse proto.InternalMessageInfo

func (m *IntrospectResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *IntrospectResponse) GetAud() []string {
	if m != nil {
		return m.Aud
	}
	return nil
}

func (m *IntrospectResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *IntrospectResponse) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *IntrospectResponse) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *IntrospectResponse) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *IntrospectResponse) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *IntrospectResponse) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *IntrospectResponse) GetObfuscatedSubject() string {
	if m != nil {
		return m.ObfuscatedSubject
	}
	return ""
}

func (m *IntrospectResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *IntrospectResponse) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *IntrospectResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *IntrospectResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RedirectResponse struct {
	RedirectTo           string   `protobuf:"bytes,1,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectResponse) Reset()         { *m = RedirectResponse{} }
func (m *RedirectResponse) String() string { return proto.CompactTextString(m) }
func (*RedirectResponse) ProtoMessage()    {}
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{5}
}

func (m *RedirectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectResponse.Unmarshal(m, b)
}
func (m *RedirectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectResponse.Marshal(b, m, deterministic)
}
func (m *RedirectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectResponse.Merge(m, src)
}
func (m *RedirectResponse) XXX_Size() int {
	return xxx_messageInfo_RedirectResponse.Size(m)
}
func (m *RedirectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectResponse proto.InternalMessageInfo

func (m *RedirectResponse) GetRedirectTo() string {
	if m != nil {
		return m.RedirectTo
	}
	return ""
}

type AccountExistsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountExistsRequest) Reset()         { *m = AccountExistsRequest{} }
func (m *AccountExistsRequest) String() string { return proto.CompactTextString(m) }
func (*AccountExistsRequest) ProtoMessage()    {}
func (*AccountExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{6}
}

func (m *AccountExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountExistsRequest.Unmarshal(m, b)
}
func (m *AccountExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountExistsRequest.Marshal(b, m, deterministic)
}
func (m *AccountExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountExistsRequest.Merge(m, src)
}
func (m *AccountExistsRequest) XXX_Size() int {
	return xxx_messageInfo_AccountExistsRequest.Size(m)
}
func (m *AccountExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountExistsRequest proto.InternalMessageInfo

func (m *AccountExistsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AccountExistsResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountExistsResponse) Reset()         { *m = AccountExistsResponse{} }
func (m *AccountExistsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountExistsResponse) ProtoMessage()    {}
func (*AccountExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{7}
}

func (m *AccountExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountExistsResponse.Unmarshal(m, b)
}
func (m *AccountExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountExistsResponse.Marshal(b, m, deterministic)
}
func (m *AccountExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountExistsResponse.Merge(m, src)
}
func (m *AccountExistsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountExistsResponse.Size(m)
}
func (m *AccountExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountExistsResponse proto.InternalMessageInfo

func (m *AccountExistsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountExistsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountExistsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AccountExistsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AccountExistsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AuthenticateResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{8}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SignUpRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{9}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type AuthenticateRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CaptchaToken         string   `protobuf:"bytes,3,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{10}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticateRequest) GetCaptchaToken() string {
	if m != nil {
		return m.CaptchaToken
	}
	return ""
}

type EmailExistsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailExistsRequest) Reset()         { *m = EmailExistsRequest{} }
func (m *EmailExistsRequest) String() string { return proto.CompactTextString(m) }
func (*EmailExistsRequest) ProtoMessage()    {}
func (*EmailExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{11}
}

func (m *EmailExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailExistsRequest.Unmarshal(m, b)
}
func (m *EmailExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailExistsRequest.Marshal(b, m, deterministic)
}
func (m *EmailExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailExistsRequest.Merge(m, src)
}
func (m *EmailExistsRequest) XXX_Size() int {
	return xxx_messageInfo_EmailExistsRequest.Size(m)
}
func (m *EmailExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailExistsRequest proto.InternalMessageInfo

func (m *EmailExistsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailExistsResponse struct {
	Exist                bool     `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailExistsResponse) Reset()         { *m = EmailExistsResponse{} }
func (m *EmailExistsResponse) String() string { return proto.CompactTextString(m) }
func (*EmailExistsResponse) ProtoMessage()    {}
func (*EmailExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8726aced901bdecf, []int{12}
}

func (m *EmailExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailExistsResponse.Unmarshal(m, b)
}
func (m *EmailExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailExistsResponse.Marshal(b, m, deterministic)
}
func (m *EmailExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailExistsResponse.Merge(m, src)
}
func (m *EmailExistsResponse) XXX_Size() int {
	return xxx_messageInfo_EmailExistsResponse.Size(m)
}
func (m *EmailExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailExistsResponse proto.InternalMessageInfo

func (m *EmailExistsResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "api.accounts.v1.Empty")
	proto.RegisterType((*Body)(nil), "api.accounts.v1.Body")
	proto.RegisterType((*HydraResponse)(nil), "api.accounts.v1.HydraResponse")
	proto.RegisterType((*IntrospectRequest)(nil), "api.accounts.v1.IntrospectRequest")
	proto.RegisterType((*IntrospectResponse)(nil), "api.accounts.v1.IntrospectResponse")
	proto.RegisterType((*RedirectResponse)(nil), "api.accounts.v1.RedirectResponse")
	proto.RegisterType((*AccountExistsRequest)(nil), "api.accounts.v1.AccountExistsRequest")
	proto.RegisterType((*AccountExistsResponse)(nil), "api.accounts.v1.AccountExistsResponse")
	proto.RegisterType((*AuthenticateResponse)(nil), "api.accounts.v1.AuthenticateResponse")
	proto.RegisterType((*SignUpRequest)(nil), "api.accounts.v1.SignUpRequest")
	proto.RegisterType((*AuthenticateRequest)(nil), "api.accounts.v1.AuthenticateRequest")
	proto.RegisterType((*EmailExistsRequest)(nil), "api.accounts.v1.EmailExistsRequest")
	proto.RegisterType((*EmailExistsResponse)(nil), "api.accounts.v1.EmailExistsResponse")
}

func init() {
	proto.RegisterFile("accounts/v1/accounts.proto", fileDescriptor_8726aced901bdecf)
}

var fileDescriptor_8726aced901bdecf = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0xda, 0x8e, 0x63, 0x9f, 0xd8, 0x4d, 0x3a, 0x35, 0xd5, 0xb2, 0x2d, 0xe0, 0x4e, 0x4a,
	0x15, 0x40, 0xd8, 0x2a, 0x7d, 0x00, 0xd4, 0x56, 0x91, 0x88, 0x04, 0x15, 0xda, 0xa4, 0xaa, 0xc4,
	0x8d, 0x19, 0xef, 0x8e, 0xed, 0xa1, 0xeb, 0x99, 0x65, 0x67, 0x36, 0xd4, 0xbd, 0xe4, 0x9e, 0x2b,
	0x5e, 0x80, 0x4b, 0x1e, 0x82, 0x7b, 0x1e, 0x80, 0x57, 0xe0, 0x41, 0xaa, 0xf9, 0xd9, 0xf5, 0x7a,
	0xed, 0x26, 0xb9, 0x9b, 0xf3, 0xcd, 0xd9, 0xf3, 0x9d, 0xef, 0xfc, 0x8c, 0x0d, 0x01, 0x89, 0x22,
	0x91, 0x73, 0x25, 0xc7, 0x97, 0x4f, 0xc6, 0xc5, 0x79, 0x94, 0x66, 0x42, 0x09, 0x74, 0x48, 0x52,
	0x36, 0x2a, 0xb1, 0xcb, 0x27, 0xc1, 0x83, 0xb9, 0x10, 0xf3, 0x84, 0x8e, 0x49, 0xca, 0xc6, 0x84,
	0x73, 0xa1, 0x88, 0x62, 0x82, 0x3b, 0xf7, 0xc0, 0xaf, 0x86, 0x92, 0xd1, 0x82, 0x2e, 0x89, 0xbd,
	0xc1, 0xfb, 0xb0, 0x77, 0xba, 0x4c, 0xd5, 0x0a, 0x0f, 0xa1, 0xf5, 0x5c, 0xc4, 0x2b, 0xe4, 0xc3,
	0x7e, 0x4a, 0x56, 0x89, 0x20, 0xb1, 0xef, 0x0d, 0xbd, 0x93, 0x5e, 0x58, 0x98, 0xf8, 0x1f, 0x0f,
	0xfa, 0xdf, 0xad, 0xe2, 0x8c, 0x84, 0x54, 0xa6, 0x82, 0x4b, 0x8a, 0x1e, 0x40, 0x37, 0x5a, 0x90,
	0x24, 0xa1, 0x7c, 0x4e, 0x8d, 0x77, 0x37, 0x5c, 0x03, 0xe8, 0x33, 0x38, 0xc8, 0xe8, 0xaf, 0x39,
	0x95, 0x6a, 0x92, 0x67, 0x89, 0xdf, 0x30, 0xf7, 0xe0, 0xa0, 0x57, 0x59, 0x82, 0x3e, 0x01, 0x90,
	0x54, 0x4a, 0x26, 0xf8, 0x84, 0xc5, 0x7e, 0xd3, 0x7e, 0xef, 0x90, 0xb3, 0x18, 0x21, 0x68, 0xc9,
	0x37, 0x2c, 0xf5, 0x5b, 0x43, 0xef, 0xa4, 0x13, 0x9a, 0xb3, 0xce, 0x4e, 0xe6, 0xd3, 0x5f, 0x68,
	0xa4, 0xfc, 0x3d, 0xe3, 0x5f, 0x98, 0x96, 0x2d, 0x66, 0x19, 0x8d, 0xd4, 0x44, 0x09, 0xbf, 0x5d,
	0xb0, 0x59, 0xe8, 0x42, 0xe0, 0x6f, 0xe1, 0xce, 0x19, 0x57, 0x99, 0x90, 0x29, 0x8d, 0x54, 0x68,
	0xb3, 0x40, 0x03, 0xd8, 0x53, 0xe2, 0x0d, 0xe5, 0x2e, 0x7b, 0x6b, 0x68, 0x54, 0x46, 0x22, 0xa5,
	0x2e, 0x67, 0x6b, 0xe0, 0x7f, 0x1b, 0x80, 0xaa, 0x11, 0x5c, 0x11, 0xee, 0x41, 0x9b, 0x44, 0x8a,
	0x5d, 0xda, 0x0a, 0x74, 0x42, 0x67, 0xa1, 0x23, 0x68, 0x92, 0x3c, 0xf6, 0x1b, 0xc3, 0xe6, 0x49,
	0x37, 0xd4, 0x47, 0x74, 0x1f, 0xba, 0x51, 0xc2, 0x28, 0x57, 0x6b, 0xb9, 0x1d, 0x0b, 0x9c, 0xc5,
	0xda, 0x9d, 0xbe, 0xb5, 0x62, 0x9b, 0xa1, 0x3e, 0x5a, 0xc4, 0xea, 0xec, 0x69, 0x44, 0x69, 0x84,
	0x11, 0x65, 0xb4, 0x35, 0x43, 0x7d, 0x34, 0x88, 0x94, 0xfe, 0xbe, 0x09, 0xa6, 0x8f, 0x1a, 0xe1,
	0xd3, 0x99, 0xdf, 0xb1, 0x3e, 0x7c, 0x3a, 0x43, 0x5f, 0x03, 0x12, 0xd3, 0x59, 0x2e, 0x23, 0xa2,
	0x68, 0x3c, 0x29, 0xca, 0xd7, 0x35, 0x9f, 0xdc, 0x59, 0xdf, 0x9c, 0xbb, 0x42, 0x96, 0xe2, 0xa1,
	0x22, 0x5e, 0x87, 0x95, 0xf9, 0xd4, 0x3f, 0xb0, 0x44, 0x32, 0x9f, 0xea, 0xee, 0x99, 0x6a, 0x4d,
	0xd4, 0x2a, 0xa5, 0x7e, 0xcf, 0x76, 0xcf, 0x20, 0x17, 0xab, 0x94, 0xa2, 0x00, 0x3a, 0xb9, 0xa4,
	0x19, 0x27, 0x4b, 0xea, 0xf7, 0xad, 0xd6, 0xc2, 0xc6, 0x4f, 0xe1, 0x28, 0x74, 0x8d, 0x29, 0xcb,
	0x58, 0xeb, 0x9f, 0xb7, 0xd5, 0xbf, 0xc7, 0x30, 0x78, 0x66, 0xa7, 0xf8, 0xf4, 0x2d, 0x93, 0x4a,
	0x16, 0x2d, 0xbc, 0x0d, 0x0d, 0x16, 0x3b, 0xff, 0x06, 0x8b, 0xf1, 0x1f, 0x1e, 0x7c, 0x54, 0x73,
	0x74, 0x14, 0x35, 0x4f, 0xad, 0x94, 0x2e, 0x09, 0x2b, 0x46, 0xd3, 0x1a, 0x5a, 0xd7, 0x8c, 0x65,
	0x52, 0x4d, 0x4c, 0xea, 0x6e, 0x2a, 0x0d, 0xf2, 0x92, 0x2c, 0xa9, 0x6e, 0x62, 0x42, 0x8a, 0xdb,
	0x96, 0x15, 0xa6, 0x01, 0x73, 0x89, 0xa0, 0x65, 0x70, 0x3b, 0x9b, 0xe6, 0x8c, 0x47, 0x30, 0x78,
	0x96, 0xab, 0x05, 0xe5, 0x8a, 0xe9, 0x3a, 0x57, 0xe7, 0x46, 0x2a, 0xa2, 0x72, 0x59, 0xcc, 0x8d,
	0xb5, 0xf0, 0xdf, 0x1e, 0xf4, 0xcf, 0xd9, 0x9c, 0xbf, 0x4a, 0x0b, 0x85, 0x9b, 0x19, 0x79, 0x57,
	0x66, 0xd4, 0xa8, 0x65, 0x54, 0x6a, 0x6c, 0x56, 0x35, 0x06, 0xd0, 0x49, 0x89, 0x94, 0xbf, 0x89,
	0x2c, 0x2e, 0x34, 0x14, 0x36, 0xfa, 0x02, 0x8e, 0x22, 0xc1, 0x67, 0x2c, 0x5b, 0x4e, 0x4a, 0x1f,
	0xab, 0xe7, 0xd0, 0xe1, 0x3f, 0x3a, 0x18, 0x27, 0x70, 0x77, 0x53, 0x5a, 0xb9, 0x54, 0x96, 0xd3,
	0xfb, 0x10, 0x67, 0xa3, 0xc6, 0x79, 0x0c, 0xfd, 0x88, 0xa4, 0x2a, 0x5a, 0x90, 0x89, 0x5d, 0x47,
	0x9b, 0x6d, 0xcf, 0x81, 0x17, 0x1a, 0xc3, 0x5f, 0x02, 0x3a, 0xd5, 0x91, 0x36, 0xdb, 0xbf, 0x93,
	0x0c, 0x7f, 0x05, 0x77, 0x37, 0x7c, 0x5d, 0xcd, 0xb5, 0xb3, 0x46, 0x5c, 0xc9, 0xad, 0xf1, 0xcd,
	0x5f, 0x6d, 0x38, 0x74, 0x13, 0x23, 0xcf, 0x69, 0x76, 0xc9, 0x22, 0x8a, 0x5e, 0x02, 0xfa, 0x5e,
	0xcc, 0x19, 0x7f, 0xcd, 0xd4, 0xe2, 0x45, 0xf9, 0xa4, 0xdd, 0x1b, 0xd5, 0xde, 0xdd, 0x91, 0x79,
	0x3c, 0x83, 0x4f, 0xb7, 0xf0, 0x8d, 0x87, 0x12, 0xdf, 0x42, 0xe7, 0x30, 0x78, 0xa1, 0x8f, 0x5c,
	0xdd, 0x2c, 0xe2, 0xc3, 0x2d, 0xbc, 0xbe, 0x31, 0xf8, 0x16, 0x7a, 0x0d, 0xb0, 0x7e, 0x90, 0x10,
	0xde, 0xfa, 0x64, 0xeb, 0xbd, 0x0b, 0x8e, 0xaf, 0xf4, 0x29, 0x03, 0xff, 0x0c, 0xfd, 0x8d, 0x15,
	0x42, 0x9f, 0x6f, 0x7d, 0xb7, 0x6b, 0x17, 0x83, 0xc7, 0xd7, 0xb9, 0x95, 0x0c, 0x33, 0x38, 0x3c,
	0x93, 0xd5, 0xe1, 0x89, 0x3f, 0x58, 0x8a, 0x1d, 0xdc, 0x3b, 0xf6, 0x09, 0x0f, 0x7e, 0xff, 0xef,
	0xff, 0x3f, 0x1b, 0xb7, 0x71, 0xaf, 0xfa, 0x73, 0x89, 0x7e, 0x80, 0xb6, 0x5d, 0x26, 0xb4, 0xdd,
	0xa3, 0x8d, 0x2d, 0xbb, 0x59, 0xc5, 0xdf, 0x41, 0xaf, 0x4a, 0x8e, 0x1e, 0x5d, 0x93, 0xdb, 0x8d,
	0x43, 0x3f, 0x34, 0xd9, 0xdf, 0xc7, 0x1f, 0x57, 0xb3, 0x1f, 0x93, 0x2a, 0xd7, 0x3b, 0x38, 0xa8,
	0xcc, 0x34, 0x3a, 0xde, 0x51, 0xae, 0xfa, 0x76, 0x04, 0x8f, 0xae, 0x76, 0x72, 0xe4, 0x43, 0x43,
	0x1e, 0x60, 0x7f, 0x83, 0xdc, 0x6c, 0xd2, 0xd8, 0xac, 0xc8, 0x73, 0xf8, 0xa9, 0x53, 0xe0, 0xd3,
	0xb6, 0xf9, 0xe7, 0xf0, 0xf4, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x8c, 0x72, 0x5b, 0xa0,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountsServiceClient is the client API for AccountsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsServiceClient interface {
	LoginWithChallenge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HydraResponse, error)
	ConsentWithChallenge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RedirectResponse, error)
	Introspect(ctx context.Context, in *IntrospectRequest, opts ...grpc.CallOption) (*IntrospectResponse, error)
	AccountExists(ctx context.Context, in *AccountExistsRequest, opts ...grpc.CallOption) (*AccountExistsResponse, error)
	IsAuthenticated(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*RedirectResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*RedirectResponse, error)
	EmailExists(ctx context.Context, in *EmailExistsRequest, opts ...grpc.CallOption) (*EmailExistsResponse, error)
}

type accountsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsServiceClient(cc grpc.ClientConnInterface) AccountsServiceClient {
	return &accountsServiceClient{cc}
}

func (c *accountsServiceClient) LoginWithChallenge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HydraResponse, error) {
	out := new(HydraResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/LoginWithChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) ConsentWithChallenge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RedirectResponse, error) {
	out := new(RedirectResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/ConsentWithChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Introspect(ctx context.Context, in *IntrospectRequest, opts ...grpc.CallOption) (*IntrospectResponse, error) {
	out := new(IntrospectResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/Introspect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) AccountExists(ctx context.Context, in *AccountExistsRequest, opts ...grpc.CallOption) (*AccountExistsResponse, error) {
	out := new(AccountExistsResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/AccountExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) IsAuthenticated(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/IsAuthenticated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*RedirectResponse, error) {
	out := new(RedirectResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*RedirectResponse, error) {
	out := new(RedirectResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) EmailExists(ctx context.Context, in *EmailExistsRequest, opts ...grpc.CallOption) (*EmailExistsResponse, error) {
	out := new(EmailExistsResponse)
	err := c.cc.Invoke(ctx, "/api.accounts.v1.AccountsService/EmailExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServiceServer is the server API for AccountsService service.
type AccountsServiceServer interface {
	LoginWithChallenge(context.Context, *Empty) (*HydraResponse, error)
	ConsentWithChallenge(context.Context, *Empty) (*RedirectResponse, error)
	Introspect(context.Context, *IntrospectRequest) (*IntrospectResponse, error)
	AccountExists(context.Context, *AccountExistsRequest) (*AccountExistsResponse, error)
	IsAuthenticated(context.Context, *Empty) (*AuthenticateResponse, error)
	SignUp(context.Context, *SignUpRequest) (*RedirectResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*RedirectResponse, error)
	EmailExists(context.Context, *EmailExistsRequest) (*EmailExistsResponse, error)
}

// UnimplementedAccountsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsServiceServer struct {
}

func (*UnimplementedAccountsServiceServer) LoginWithChallenge(ctx context.Context, req *Empty) (*HydraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithChallenge not implemented")
}
func (*UnimplementedAccountsServiceServer) ConsentWithChallenge(ctx context.Context, req *Empty) (*RedirectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsentWithChallenge not implemented")
}
func (*UnimplementedAccountsServiceServer) Introspect(ctx context.Context, req *IntrospectRequest) (*IntrospectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Introspect not implemented")
}
func (*UnimplementedAccountsServiceServer) AccountExists(ctx context.Context, req *AccountExistsRequest) (*AccountExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountExists not implemented")
}
func (*UnimplementedAccountsServiceServer) IsAuthenticated(ctx context.Context, req *Empty) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthenticated not implemented")
}
func (*UnimplementedAccountsServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*RedirectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAccountsServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*RedirectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAccountsServiceServer) EmailExists(ctx context.Context, req *EmailExistsRequest) (*EmailExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailExists not implemented")
}

func RegisterAccountsServiceServer(s *grpc.Server, srv AccountsServiceServer) {
	s.RegisterService(&_AccountsService_serviceDesc, srv)
}

func _AccountsService_LoginWithChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).LoginWithChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/LoginWithChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).LoginWithChallenge(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_ConsentWithChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).ConsentWithChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/ConsentWithChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).ConsentWithChallenge(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Introspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Introspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/Introspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Introspect(ctx, req.(*IntrospectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_AccountExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).AccountExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/AccountExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).AccountExists(ctx, req.(*AccountExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_IsAuthenticated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).IsAuthenticated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/IsAuthenticated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).IsAuthenticated(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_EmailExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).EmailExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.accounts.v1.AccountsService/EmailExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).EmailExists(ctx, req.(*EmailExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.accounts.v1.AccountsService",
	HandlerType: (*AccountsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginWithChallenge",
			Handler:    _AccountsService_LoginWithChallenge_Handler,
		},
		{
			MethodName: "ConsentWithChallenge",
			Handler:    _AccountsService_ConsentWithChallenge_Handler,
		},
		{
			MethodName: "Introspect",
			Handler:    _AccountsService_Introspect_Handler,
		},
		{
			MethodName: "AccountExists",
			Handler:    _AccountsService_AccountExists_Handler,
		},
		{
			MethodName: "IsAuthenticated",
			Handler:    _AccountsService_IsAuthenticated_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _AccountsService_SignUp_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AccountsService_Authenticate_Handler,
		},
		{
			MethodName: "EmailExists",
			Handler:    _AccountsService_EmailExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/v1/accounts.proto",
}
