// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/v1/schema.proto

package accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Preferences
type Preferences struct {
	Language             string                          `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	EmailNotifications   *Preferences_EmailNotifications `protobuf:"bytes,2,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	PushNotifications    *Preferences_PushNotifications  `protobuf:"bytes,3,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Preferences) Reset()         { *m = Preferences{} }
func (m *Preferences) String() string { return proto.CompactTextString(m) }
func (*Preferences) ProtoMessage()    {}
func (*Preferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{0}
}

func (m *Preferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preferences.Unmarshal(m, b)
}
func (m *Preferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preferences.Marshal(b, m, deterministic)
}
func (m *Preferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preferences.Merge(m, src)
}
func (m *Preferences) XXX_Size() int {
	return xxx_messageInfo_Preferences.Size(m)
}
func (m *Preferences) XXX_DiscardUnknown() {
	xxx_messageInfo_Preferences.DiscardUnknown(m)
}

var xxx_messageInfo_Preferences proto.InternalMessageInfo

func (m *Preferences) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Preferences) GetEmailNotifications() *Preferences_EmailNotifications {
	if m != nil {
		return m.EmailNotifications
	}
	return nil
}

func (m *Preferences) GetPushNotifications() *Preferences_PushNotifications {
	if m != nil {
		return m.PushNotifications
	}
	return nil
}

type Preferences_EmailNotifications struct {
	UnsubscribeFromAll   bool     `protobuf:"varint,1,opt,name=unsubscribe_from_all,json=unsubscribeFromAll,proto3" json:"unsubscribe_from_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preferences_EmailNotifications) Reset()         { *m = Preferences_EmailNotifications{} }
func (m *Preferences_EmailNotifications) String() string { return proto.CompactTextString(m) }
func (*Preferences_EmailNotifications) ProtoMessage()    {}
func (*Preferences_EmailNotifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{0, 0}
}

func (m *Preferences_EmailNotifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preferences_EmailNotifications.Unmarshal(m, b)
}
func (m *Preferences_EmailNotifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preferences_EmailNotifications.Marshal(b, m, deterministic)
}
func (m *Preferences_EmailNotifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preferences_EmailNotifications.Merge(m, src)
}
func (m *Preferences_EmailNotifications) XXX_Size() int {
	return xxx_messageInfo_Preferences_EmailNotifications.Size(m)
}
func (m *Preferences_EmailNotifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Preferences_EmailNotifications.DiscardUnknown(m)
}

var xxx_messageInfo_Preferences_EmailNotifications proto.InternalMessageInfo

func (m *Preferences_EmailNotifications) GetUnsubscribeFromAll() bool {
	if m != nil {
		return m.UnsubscribeFromAll
	}
	return false
}

type Preferences_PushNotifications struct {
	UnsubscribeFromAll   bool     `protobuf:"varint,1,opt,name=unsubscribe_from_all,json=unsubscribeFromAll,proto3" json:"unsubscribe_from_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preferences_PushNotifications) Reset()         { *m = Preferences_PushNotifications{} }
func (m *Preferences_PushNotifications) String() string { return proto.CompactTextString(m) }
func (*Preferences_PushNotifications) ProtoMessage()    {}
func (*Preferences_PushNotifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{0, 1}
}

func (m *Preferences_PushNotifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preferences_PushNotifications.Unmarshal(m, b)
}
func (m *Preferences_PushNotifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preferences_PushNotifications.Marshal(b, m, deterministic)
}
func (m *Preferences_PushNotifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preferences_PushNotifications.Merge(m, src)
}
func (m *Preferences_PushNotifications) XXX_Size() int {
	return xxx_messageInfo_Preferences_PushNotifications.Size(m)
}
func (m *Preferences_PushNotifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Preferences_PushNotifications.DiscardUnknown(m)
}

var xxx_messageInfo_Preferences_PushNotifications proto.InternalMessageInfo

func (m *Preferences_PushNotifications) GetUnsubscribeFromAll() bool {
	if m != nil {
		return m.UnsubscribeFromAll
	}
	return false
}

type ProfileName struct {
	FamilyName           string   `protobuf:"bytes,1,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,2,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileName) Reset()         { *m = ProfileName{} }
func (m *ProfileName) String() string { return proto.CompactTextString(m) }
func (*ProfileName) ProtoMessage()    {}
func (*ProfileName) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{1}
}

func (m *ProfileName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileName.Unmarshal(m, b)
}
func (m *ProfileName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileName.Marshal(b, m, deterministic)
}
func (m *ProfileName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileName.Merge(m, src)
}
func (m *ProfileName) XXX_Size() int {
	return xxx_messageInfo_ProfileName.Size(m)
}
func (m *ProfileName) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileName.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileName proto.InternalMessageInfo

func (m *ProfileName) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *ProfileName) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *ProfileName) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

type ProfileEmails struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileEmails) Reset()         { *m = ProfileEmails{} }
func (m *ProfileEmails) String() string { return proto.CompactTextString(m) }
func (*ProfileEmails) ProtoMessage()    {}
func (*ProfileEmails) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{2}
}

func (m *ProfileEmails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileEmails.Unmarshal(m, b)
}
func (m *ProfileEmails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileEmails.Marshal(b, m, deterministic)
}
func (m *ProfileEmails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileEmails.Merge(m, src)
}
func (m *ProfileEmails) XXX_Size() int {
	return xxx_messageInfo_ProfileEmails.Size(m)
}
func (m *ProfileEmails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileEmails.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileEmails proto.InternalMessageInfo

func (m *ProfileEmails) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ProfileEmails) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ProfilePhotos struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePhotos) Reset()         { *m = ProfilePhotos{} }
func (m *ProfilePhotos) String() string { return proto.CompactTextString(m) }
func (*ProfilePhotos) ProtoMessage()    {}
func (*ProfilePhotos) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{3}
}

func (m *ProfilePhotos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePhotos.Unmarshal(m, b)
}
func (m *ProfilePhotos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePhotos.Marshal(b, m, deterministic)
}
func (m *ProfilePhotos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePhotos.Merge(m, src)
}
func (m *ProfilePhotos) XXX_Size() int {
	return xxx_messageInfo_ProfilePhotos.Size(m)
}
func (m *ProfilePhotos) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePhotos.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePhotos proto.InternalMessageInfo

func (m *ProfilePhotos) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserProfileFacebook struct {
	Provider             string           `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id                   string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string           `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Name                 *ProfileName     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Emails               []*ProfileEmails `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Photos               []*ProfilePhotos `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserProfileFacebook) Reset()         { *m = UserProfileFacebook{} }
func (m *UserProfileFacebook) String() string { return proto.CompactTextString(m) }
func (*UserProfileFacebook) ProtoMessage()    {}
func (*UserProfileFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{4}
}

func (m *UserProfileFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileFacebook.Unmarshal(m, b)
}
func (m *UserProfileFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileFacebook.Marshal(b, m, deterministic)
}
func (m *UserProfileFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileFacebook.Merge(m, src)
}
func (m *UserProfileFacebook) XXX_Size() int {
	return xxx_messageInfo_UserProfileFacebook.Size(m)
}
func (m *UserProfileFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileFacebook proto.InternalMessageInfo

func (m *UserProfileFacebook) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *UserProfileFacebook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfileFacebook) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserProfileFacebook) GetName() *ProfileName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UserProfileFacebook) GetEmails() []*ProfileEmails {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UserProfileFacebook) GetPhotos() []*ProfilePhotos {
	if m != nil {
		return m.Photos
	}
	return nil
}

type UserProfileGoogle struct {
	Provider             string           `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id                   string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string           `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Name                 *ProfileName     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Emails               []*ProfileEmails `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Photos               []*ProfilePhotos `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserProfileGoogle) Reset()         { *m = UserProfileGoogle{} }
func (m *UserProfileGoogle) String() string { return proto.CompactTextString(m) }
func (*UserProfileGoogle) ProtoMessage()    {}
func (*UserProfileGoogle) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{5}
}

func (m *UserProfileGoogle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileGoogle.Unmarshal(m, b)
}
func (m *UserProfileGoogle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileGoogle.Marshal(b, m, deterministic)
}
func (m *UserProfileGoogle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileGoogle.Merge(m, src)
}
func (m *UserProfileGoogle) XXX_Size() int {
	return xxx_messageInfo_UserProfileGoogle.Size(m)
}
func (m *UserProfileGoogle) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileGoogle.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileGoogle proto.InternalMessageInfo

func (m *UserProfileGoogle) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *UserProfileGoogle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfileGoogle) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserProfileGoogle) GetName() *ProfileName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UserProfileGoogle) GetEmails() []*ProfileEmails {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UserProfileGoogle) GetPhotos() []*ProfilePhotos {
	if m != nil {
		return m.Photos
	}
	return nil
}

type Auth struct {
	Facebook                 *UserProfileFacebook `protobuf:"bytes,1,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Google                   *UserProfileGoogle   `protobuf:"bytes,2,opt,name=google,proto3" json:"google,omitempty"`
	Email                    string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName                string               `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                 string               `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Name                     string               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Picture                  string               `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	Password                 string               `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	PasswordHashMethod       string               `protobuf:"bytes,9,opt,name=password_hash_method,json=passwordHashMethod,proto3" json:"password_hash_method,omitempty"`
	PasswordResetId          string               `protobuf:"bytes,10,opt,name=password_reset_id,json=passwordResetId,proto3" json:"password_reset_id,omitempty"`
	PasswordResetToken       string               `protobuf:"bytes,11,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	PasswordResetExpires     int64                `protobuf:"varint,12,opt,name=password_reset_expires,json=passwordResetExpires,proto3" json:"password_reset_expires,omitempty"`
	PasswordModified         int64                `protobuf:"varint,13,opt,name=password_modified,json=passwordModified,proto3" json:"password_modified,omitempty"`
	Verified                 bool                 `protobuf:"varint,14,opt,name=verified,proto3" json:"verified,omitempty"`
	VerifiedDate             int64                `protobuf:"varint,15,opt,name=verified_date,json=verifiedDate,proto3" json:"verified_date,omitempty"`
	VerificationToken        string               `protobuf:"bytes,16,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	VerificationTokenExpires int64                `protobuf:"varint,17,opt,name=verification_token_expires,json=verificationTokenExpires,proto3" json:"verification_token_expires,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}             `json:"-"`
	XXX_unrecognized         []byte               `json:"-"`
	XXX_sizecache            int32                `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{6}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetFacebook() *UserProfileFacebook {
	if m != nil {
		return m.Facebook
	}
	return nil
}

func (m *Auth) GetGoogle() *UserProfileGoogle {
	if m != nil {
		return m.Google
	}
	return nil
}

func (m *Auth) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Auth) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Auth) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Auth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Auth) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Auth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Auth) GetPasswordHashMethod() string {
	if m != nil {
		return m.PasswordHashMethod
	}
	return ""
}

func (m *Auth) GetPasswordResetId() string {
	if m != nil {
		return m.PasswordResetId
	}
	return ""
}

func (m *Auth) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

func (m *Auth) GetPasswordResetExpires() int64 {
	if m != nil {
		return m.PasswordResetExpires
	}
	return 0
}

func (m *Auth) GetPasswordModified() int64 {
	if m != nil {
		return m.PasswordModified
	}
	return 0
}

func (m *Auth) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Auth) GetVerifiedDate() int64 {
	if m != nil {
		return m.VerifiedDate
	}
	return 0
}

func (m *Auth) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

func (m *Auth) GetVerificationTokenExpires() int64 {
	if m != nil {
		return m.VerificationTokenExpires
	}
	return 0
}

type Session struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Lat                  int32    `protobuf:"varint,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 int32    `protobuf:"varint,5,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{7}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Session) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Session) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Session) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Session) GetLong() int32 {
	if m != nil {
		return m.Long
	}
	return 0
}

type Account struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               string       `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Auth                 *Auth        `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Preferences          *Preferences `protobuf:"bytes,4,opt,name=preferences,proto3" json:"preferences,omitempty"`
	CreatedAt            int64        `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LoggedIn             int64        `protobuf:"varint,7,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	Sessions             []*Session   `protobuf:"bytes,8,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd05833f6698f1a, []int{8}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Account) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *Account) GetPreferences() *Preferences {
	if m != nil {
		return m.Preferences
	}
	return nil
}

func (m *Account) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Account) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Account) GetLoggedIn() int64 {
	if m != nil {
		return m.LoggedIn
	}
	return 0
}

func (m *Account) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Preferences)(nil), "api.accounts.v1.Preferences")
	proto.RegisterType((*Preferences_EmailNotifications)(nil), "api.accounts.v1.Preferences.EmailNotifications")
	proto.RegisterType((*Preferences_PushNotifications)(nil), "api.accounts.v1.Preferences.PushNotifications")
	proto.RegisterType((*ProfileName)(nil), "api.accounts.v1.ProfileName")
	proto.RegisterType((*ProfileEmails)(nil), "api.accounts.v1.ProfileEmails")
	proto.RegisterType((*ProfilePhotos)(nil), "api.accounts.v1.ProfilePhotos")
	proto.RegisterType((*UserProfileFacebook)(nil), "api.accounts.v1.UserProfileFacebook")
	proto.RegisterType((*UserProfileGoogle)(nil), "api.accounts.v1.UserProfileGoogle")
	proto.RegisterType((*Auth)(nil), "api.accounts.v1.Auth")
	proto.RegisterType((*Session)(nil), "api.accounts.v1.Session")
	proto.RegisterType((*Account)(nil), "api.accounts.v1.Account")
}

func init() {
	proto.RegisterFile("accounts/v1/schema.proto", fileDescriptor_4cd05833f6698f1a)
}

var fileDescriptor_4cd05833f6698f1a = []byte{
	// 900 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x57, 0x9d, 0x3f, 0x4d, 0x26, 0xed, 0xb5, 0xd9, 0x2b, 0xa7, 0x55, 0x39, 0xa0, 0x18, 0x90,
	0x0a, 0x88, 0xf4, 0xae, 0x20, 0x24, 0x10, 0x42, 0x04, 0xd1, 0xc2, 0x3d, 0xdc, 0xa9, 0x5a, 0xe0,
	0x05, 0x09, 0x99, 0x8d, 0xbd, 0x89, 0x97, 0xb3, 0xbd, 0x96, 0x77, 0x1d, 0xe8, 0x3b, 0xe2, 0xdb,
	0xf0, 0x21, 0xf8, 0x58, 0xbc, 0xa1, 0x9d, 0xdd, 0xf5, 0xa5, 0xcd, 0x5d, 0x25, 0x9e, 0x79, 0xf3,
	0xcc, 0x6f, 0x7e, 0x33, 0x9e, 0x5f, 0x66, 0xc6, 0x01, 0xca, 0xd3, 0x54, 0xb5, 0x95, 0xd1, 0x67,
	0xeb, 0xc7, 0x67, 0x3a, 0xcd, 0x45, 0xc9, 0x67, 0x75, 0xa3, 0x8c, 0x22, 0x07, 0xbc, 0x96, 0xb3,
	0x80, 0xce, 0xd6, 0x8f, 0xe3, 0x7f, 0x22, 0x98, 0x5c, 0x35, 0x62, 0x29, 0x1a, 0x51, 0xa5, 0x42,
	0x93, 0x63, 0x18, 0x15, 0xbc, 0x5a, 0xb5, 0x7c, 0x25, 0xe8, 0xce, 0xc9, 0xce, 0xe9, 0x98, 0x75,
	0x36, 0xf9, 0x05, 0xee, 0x8b, 0x92, 0xcb, 0x22, 0xa9, 0x94, 0x91, 0x4b, 0x99, 0x72, 0x23, 0x55,
	0xa5, 0x69, 0x74, 0xb2, 0x73, 0x3a, 0x39, 0x3f, 0x9b, 0xdd, 0x4a, 0x3d, 0xdb, 0x48, 0x3b, 0xbb,
	0xb0, 0xbc, 0x67, 0x9b, 0x34, 0x46, 0xc4, 0x96, 0x8f, 0xfc, 0x0c, 0xa4, 0x6e, 0x75, 0x7e, 0xab,
	0x40, 0x0f, 0x0b, 0xcc, 0xee, 0x2c, 0x70, 0xd5, 0xea, 0xfc, 0x66, 0xfe, 0x69, 0x7d, 0xdb, 0x75,
	0x7c, 0x09, 0x64, 0xfb, 0x45, 0xc8, 0x23, 0x38, 0x6a, 0x2b, 0xdd, 0x2e, 0x74, 0xda, 0xc8, 0x85,
	0x48, 0x96, 0x8d, 0x2a, 0x13, 0x5e, 0x14, 0xd8, 0xfe, 0x88, 0x91, 0x0d, 0xec, 0xb2, 0x51, 0xe5,
	0xbc, 0x28, 0x8e, 0x2f, 0x60, 0xba, 0x55, 0xef, 0xbf, 0xa7, 0x89, 0x2b, 0x2b, 0xbd, 0x5a, 0xca,
	0x42, 0x3c, 0xe3, 0xa5, 0x20, 0x6f, 0xc1, 0x64, 0xc9, 0x4b, 0x59, 0x5c, 0x27, 0x15, 0x2f, 0x83,
	0xfa, 0xe0, 0x5c, 0x18, 0xf0, 0x06, 0xc0, 0x4a, 0xae, 0x45, 0xe5, 0xf0, 0x08, 0xf1, 0x31, 0x7a,
	0x02, 0xbf, 0x94, 0x59, 0x56, 0x08, 0x87, 0xf7, 0x1c, 0xdf, 0xb9, 0x6c, 0x40, 0xfc, 0x19, 0xec,
	0xfb, 0x7a, 0xa8, 0x82, 0x26, 0x47, 0x30, 0x58, 0xf3, 0xa2, 0x0d, 0xb5, 0x9c, 0x41, 0x08, 0xf4,
	0xcd, 0x75, 0x1d, 0x0a, 0xe0, 0x73, 0xfc, 0x5e, 0x47, 0xbd, 0xca, 0x95, 0x51, 0xaf, 0xa0, 0xc6,
	0x7f, 0x46, 0x70, 0xff, 0x47, 0x2d, 0x1a, 0x1f, 0x7b, 0xc9, 0x53, 0xb1, 0x50, 0xea, 0xb9, 0x9d,
	0xaa, 0xba, 0x51, 0x6b, 0x99, 0x89, 0x26, 0x4c, 0x55, 0xb0, 0xc9, 0x3d, 0x88, 0x64, 0xe6, 0x8b,
	0x45, 0x32, 0x23, 0x6f, 0xc3, 0x5e, 0x26, 0x75, 0x5d, 0xf0, 0xeb, 0xcd, 0x3e, 0x26, 0xde, 0x87,
	0x9d, 0x3e, 0x82, 0x3e, 0x42, 0x7d, 0x1c, 0x8c, 0x87, 0x2f, 0x19, 0x8c, 0x4e, 0x55, 0x86, 0x91,
	0xe4, 0x53, 0x18, 0xe2, 0xb8, 0x69, 0x3a, 0x38, 0xe9, 0x9d, 0x4e, 0xce, 0xdf, 0x7c, 0x15, 0xc7,
	0x29, 0xc3, 0x7c, 0xb4, 0xe5, 0xd5, 0xd8, 0x30, 0x1d, 0xde, 0xcd, 0x73, 0xb2, 0x30, 0x1f, 0x1d,
	0xff, 0x11, 0xc1, 0x74, 0x43, 0x88, 0x6f, 0x95, 0x5a, 0x15, 0xe2, 0xff, 0x27, 0xc3, 0xdf, 0x03,
	0xe8, 0xcf, 0x5b, 0x93, 0x93, 0xaf, 0x60, 0xb4, 0xf4, 0xc3, 0x80, 0x9d, 0x4f, 0xce, 0xdf, 0xdd,
	0x4a, 0xf1, 0x92, 0xc1, 0x61, 0x1d, 0x8b, 0x7c, 0x0e, 0xc3, 0x15, 0xaa, 0xe8, 0xef, 0x4d, 0x7c,
	0x17, 0xdf, 0xe9, 0xcd, 0x3c, 0xc3, 0x0e, 0x2b, 0x36, 0xe2, 0x45, 0x74, 0x86, 0x5d, 0xa7, 0xa5,
	0x6c, 0xb4, 0x49, 0x3a, 0x11, 0xc7, 0x6c, 0x8c, 0x1e, 0x54, 0xf7, 0x75, 0x18, 0x17, 0x3c, 0xa0,
	0x83, 0x70, 0x0a, 0x3d, 0x48, 0xbc, 0xf4, 0x43, 0xb7, 0x23, 0x28, 0x2e, 0x85, 0xdd, 0x5a, 0xa6,
	0xa6, 0x6d, 0x04, 0xdd, 0x45, 0x77, 0x30, 0xf1, 0x77, 0xe7, 0x5a, 0xff, 0xa6, 0x9a, 0x8c, 0x8e,
	0xfc, 0xef, 0xee, 0x6d, 0x7b, 0x36, 0xc2, 0x73, 0x92, 0x73, 0x9d, 0x27, 0xa5, 0x30, 0xb9, 0xca,
	0xe8, 0x18, 0xe3, 0x48, 0xc0, 0xbe, 0xe3, 0x3a, 0x7f, 0x8a, 0x08, 0xf9, 0x00, 0xa6, 0x1d, 0xa3,
	0x11, 0x5a, 0x98, 0x44, 0x66, 0x14, 0x30, 0xfc, 0x20, 0x00, 0xcc, 0xfa, 0x9f, 0xdc, 0xcc, 0xee,
	0x62, 0x8d, 0x7a, 0x2e, 0x2a, 0x3a, 0xb9, 0x99, 0x1d, 0xc3, 0x7f, 0xb0, 0x08, 0xf9, 0x04, 0x1e,
	0xdc, 0x62, 0x88, 0xdf, 0x6b, 0xd9, 0x08, 0x4d, 0xf7, 0x4e, 0x76, 0x4e, 0x7b, 0xec, 0xe8, 0x06,
	0xe7, 0xc2, 0x61, 0xe4, 0xc3, 0x8d, 0x77, 0x2a, 0x55, 0x26, 0x97, 0x52, 0x64, 0x74, 0x1f, 0x09,
	0x87, 0x01, 0x78, 0xea, 0xfd, 0x56, 0x8e, 0xb5, 0x68, 0x5c, 0xcc, 0x3d, 0xbc, 0x8e, 0x9d, 0x4d,
	0xde, 0x81, 0xfd, 0xf0, 0x9c, 0x64, 0xdc, 0x08, 0x7a, 0x80, 0x49, 0xf6, 0x82, 0xf3, 0x1b, 0x6e,
	0x04, 0xf9, 0x08, 0x88, 0xb3, 0xdd, 0xed, 0xf5, 0x3d, 0x1d, 0x62, 0x4f, 0xd3, 0x4d, 0xc4, 0xb5,
	0xf4, 0x05, 0x1c, 0x6f, 0x87, 0x77, 0x6d, 0x4d, 0xb1, 0x00, 0xdd, 0xa2, 0xf9, 0xd6, 0xe2, 0x6b,
	0xd8, 0xfd, 0x5e, 0x68, 0x2d, 0x55, 0x85, 0x3b, 0x5a, 0xfb, 0xcd, 0x8d, 0x64, 0x4d, 0x1e, 0xc2,
	0xd8, 0xc8, 0x52, 0x68, 0xc3, 0xcb, 0x1a, 0xc7, 0xb2, 0xc7, 0x5e, 0x38, 0xf0, 0x53, 0xaa, 0x5c,
	0x42, 0x3f, 0x78, 0x9d, 0x4d, 0x0e, 0xa1, 0x57, 0x70, 0x83, 0x43, 0x37, 0x60, 0xf6, 0xd1, 0x4e,
	0x54, 0xa1, 0xaa, 0x15, 0x4e, 0xda, 0x80, 0xe1, 0x73, 0xfc, 0x57, 0x04, 0xbb, 0x73, 0x37, 0xe1,
	0xfe, 0x3e, 0xec, 0x74, 0xf7, 0xe1, 0x01, 0x0c, 0xd5, 0xe2, 0x57, 0x91, 0x1a, 0x7f, 0x33, 0xbc,
	0x45, 0xde, 0x87, 0x3e, 0x6f, 0x4d, 0xee, 0x3f, 0x9a, 0xaf, 0x6d, 0x6d, 0x89, 0x5d, 0x47, 0x86,
	0x21, 0xe4, 0x4b, 0x98, 0xd4, 0x2f, 0x3e, 0xa1, 0x77, 0x9c, 0x91, 0x2e, 0x86, 0x6d, 0x12, 0xec,
	0x02, 0xa5, 0x8d, 0xe0, 0x46, 0x64, 0x09, 0x37, 0xf8, 0xe2, 0x3d, 0x36, 0xf6, 0x9e, 0xb9, 0xb1,
	0x70, 0x5b, 0x67, 0x01, 0x1e, 0x3a, 0xd8, 0x7b, 0xe6, 0x06, 0xf7, 0x4b, 0xad, 0x56, 0x22, 0x4b,
	0x64, 0x85, 0x0b, 0xd3, 0xb3, 0xfa, 0x58, 0xc7, 0x13, 0x3b, 0x85, 0x23, 0xed, 0x44, 0xd7, 0x74,
	0x84, 0x27, 0x87, 0x6e, 0xbd, 0x97, 0xff, 0x55, 0x58, 0x17, 0xf9, 0x35, 0xfc, 0x34, 0x0a, 0x01,
	0x8b, 0x21, 0xfe, 0xe1, 0xf9, 0xf8, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xb4, 0xef, 0xf9,
	0x0c, 0x09, 0x00, 0x00,
}
