##################################################
## Gateway Service
##################################################

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  ports:
    - name: http
      port: 5000
      targetPort: gateway-port
    - name: https
      port: 443
      targetPort: webhook-port
    # - name: admin
    #   port: 8080
    #   targetPort: admin-port
  selector:
    app: gateway
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env-configmap
  namespace: default
data:
  APP_ENV: "development"
  ADDRESS: ":5000"

  WEBHOOK_ADDRESS: ":8443"
  WEBHOOK_KEY_DIR: "/run/secrets/tls/tls.key"
  WEBHOOK_CERT_DIR: "/run/secrets/tls/tls.crt"

  ACCOUNTS_DISABLE: "true"
  ACCOUNTS_ADDRESS: "api-accounts-v1-accountsservice.default.svc.cluster.local:5000"
  ACCOUNTS_TIMEOUT: "10"

  DISABLE_K8S_CLIENT: "false"
  ENABLE_STACKDRIVER: "false"

  PROTO_MAP: "api/map.json"

  # Redis
  REDIS_ADDR: 'redis-gateway.redis-gateway-service:6379'

---
# Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: api-gateway
      containers:
        - name: gateway
          image: registry.gitlab.com/eco_system/gateway
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway-port
              containerPort: 5000
            - name: webhook-port
              containerPort: 8443
            # - name: admin-port
            #   containerPort: 8080

          envFrom:
            - configMapRef:
                name: gateway-env-configmap
#            - secretRef:
#                name: gateway-env-secrets
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true

          livenessProbe:
            httpGet:
              path: /hz
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 120

      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls

      imagePullSecrets:
        - name: gitlab-auth

---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: default
---
# Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: api-gateway
rules:
  - apiGroups: ['', 'extensions', 'apps']
    resources: ['services', 'namespaces']
    verbs: ['get', 'list']

---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: api-gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-gateway
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: default

---
##################################################
## Gateway Webhook
##################################################

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gateway-webhook
  namespace: default
webhooks:
  - name: gateway-service.default.svc
    clientConfig:
      service:
        name: gateway-service
        namespace: default
        path: '/admission'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzRENDQVpnQ0NRRDVkMXBpUUtSTTFUQU5CZ2txaGtpRzl3MEJBUXNGQURBYU1SZ3dGZ1lEVlFRS0RBOW4KWVhSbGQyRjVMWE5sY25acFkyVXdIaGNOTWpFd056RTRNVGd5TkRFeFdoY05NekV3TnpFMk1UZ3lOREV4V2pBYQpNUmd3RmdZRFZRUUtEQTluWVhSbGQyRjVMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRFdVTVBnT2E0OFJHSndtak9lcXAva0liVjUxUVBFbVVuai92bWpDY011STF6Vm1hRjEKdk9sdlg1TlFjTkhBc3VmRlBTb21FRlA5QVBPK0U4SUErU29CR3IyRWI3Mi84cDEwUkZPbWZ2NVdSS2dWeVlUegprOVNaL1c5UTZRM1RWL0ZyRTJjL0RuMUpEeWVzZDBrWm5FRzhUVjlEL0o5c084RmlKMC9BcVR0aHR6b3VIdmh1CkNzdHhkT0tkNDNwUFlhSTJNaHQ5c1lpMytGUzhqcml0QW1jV0N0aVN1OHVpRHdTci9vYURUVk9kZDByRURXdUsKQjZvVnhYSjY5cGZhbVRRRGxYT1V0SGdSdWY1Tk9YZFFHMzh0ZWxNcVhlNnplUG54bmM2UVJTVjZqVVlsQTRSVApraWt2bWIxbld5a3ZVVlRpVVFHV3p2eGFpQTRxZGpwblcrb1BBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRm5HMksyU0RUN1pVWDl2VTlNbk5lZHRybHJFWlFzL3Faa3ZYS0xkV2hiVTFoSnBrS0NXQjY4U2xRNGEKaXU5RnU0cjVSVVdiN0plTUdwYU5iZWt0ckF2YzJXaFZVWEQ3L0xIWTZ5QkM0enBzZkh2NFFaN1JwbXRGenQrNwpHdkJvYlNLb3lmWHVHYmV0THZueUN3ZFBhcmc0Y3NNYmhnUy9XekpRN2xTeHdoeWZtWHAwTE0rYUhVUytjZkJsCjJCYnc3VlF2aEZxRGJSNmZ0K1Zid1dnUFJsWURyNHJqYTB6M3dQclpnMUgzKytQMjd5QkRtblNqT1N6c3VPc2UKejlPZE9aWkhuNzNrTDZEUzViRTY3b1RSeTQ0Mjg1aldxTlE5TzFPQng0Q2Z5cmh1eVFjQUZGcldTOTFnQ2ljOQovK1FMWXE4TXdWaVBPekUxakwyT2hmUHNZQkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ['*']
        apiGroups: ['*']
        apiVersions: ['*']
        resources: ['services']
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzRENDQVpnQ0NRRDVkMXBpUUtSTTFUQU5CZ2txaGtpRzl3MEJBUXNGQURBYU1SZ3dGZ1lEVlFRS0RBOW4KWVhSbGQyRjVMWE5sY25acFkyVXdIaGNOTWpFd056RTRNVGd5TkRFeFdoY05NekV3TnpFMk1UZ3lOREV4V2pBYQpNUmd3RmdZRFZRUUtEQTluWVhSbGQyRjVMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRFdVTVBnT2E0OFJHSndtak9lcXAva0liVjUxUVBFbVVuai92bWpDY011STF6Vm1hRjEKdk9sdlg1TlFjTkhBc3VmRlBTb21FRlA5QVBPK0U4SUErU29CR3IyRWI3Mi84cDEwUkZPbWZ2NVdSS2dWeVlUegprOVNaL1c5UTZRM1RWL0ZyRTJjL0RuMUpEeWVzZDBrWm5FRzhUVjlEL0o5c084RmlKMC9BcVR0aHR6b3VIdmh1CkNzdHhkT0tkNDNwUFlhSTJNaHQ5c1lpMytGUzhqcml0QW1jV0N0aVN1OHVpRHdTci9vYURUVk9kZDByRURXdUsKQjZvVnhYSjY5cGZhbVRRRGxYT1V0SGdSdWY1Tk9YZFFHMzh0ZWxNcVhlNnplUG54bmM2UVJTVjZqVVlsQTRSVApraWt2bWIxbld5a3ZVVlRpVVFHV3p2eGFpQTRxZGpwblcrb1BBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRm5HMksyU0RUN1pVWDl2VTlNbk5lZHRybHJFWlFzL3Faa3ZYS0xkV2hiVTFoSnBrS0NXQjY4U2xRNGEKaXU5RnU0cjVSVVdiN0plTUdwYU5iZWt0ckF2YzJXaFZVWEQ3L0xIWTZ5QkM0enBzZkh2NFFaN1JwbXRGenQrNwpHdkJvYlNLb3lmWHVHYmV0THZueUN3ZFBhcmc0Y3NNYmhnUy9XekpRN2xTeHdoeWZtWHAwTE0rYUhVUytjZkJsCjJCYnc3VlF2aEZxRGJSNmZ0K1Zid1dnUFJsWURyNHJqYTB6M3dQclpnMUgzKytQMjd5QkRtblNqT1N6c3VPc2UKejlPZE9aWkhuNzNrTDZEUzViRTY3b1RSeTQ0Mjg1aldxTlE5TzFPQng0Q2Z5cmh1eVFjQUZGcldTOTFnQ2ljOQovK1FMWXE4TXdWaVBPekUxakwyT2hmUHNZQkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQWRXZ0F3SUJBZ0lKQUtmelZUTmN2c25JTUEwR0NTcUdTSWIzRFFFQkJRVUFNQm94R0RBV0JnTlYKQkFvTUQyZGhkR1YzWVhrdGMyVnlkbWxqWlRBZUZ3MHlNVEEzTVRneE9ESTBNVEZhRncweU1UQTRNVGN4T0RJMApNVEZhTUNZeEpEQWlCZ05WQkFNTUcyZGhkR1YzWVhrdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMll6Q0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNK3QzZzJEaHluNkZTM1BMRlVSd2VHaENhU2MKcFNkMGFmVVcvYURka29xbm1kMWc1SkZsdXU0TlNMTmhQN0oxU1hMRXJaTktGV3RTeHkyZXB6Mk9IOEJ0Q2FUbQpoT3VDYTdJa1JkTVV2R3FtaWFNUFM4VGhoTEROZ2E0NzV1dkZ3Vk8yWGJKTEFITkpia3pRQTZoSnhSWUc3UkFBCjFGYUtVV1ZyQ0taUENYempHaEhZZlU1ekhsRlpaOU1lMlEza09JOVRkbWliUWRJcjk1WXlRVFNEb05XQ3pTYUYKZ05HQW5rYTdDdm4zcUsyZU5xb3VzZGxVK0ZMYkEvUTJXbSt4V08vZVZHMkNKM25KaGhodTZQamdOWHVMZmxUeQphOUVadldHY3hPYkk0bldLaU4yUkJPZTlaUnE2YUpIYWlSdjFnM0l6clhLdEgvamZ2R0xrdVpEbUhEa0NBd0VBCkFhTXFNQ2d3SmdZRFZSMFJCQjh3SFlJYloyRjBaWGRoZVMxelpYSjJhV05sTG1SbFptRjFiSFF1YzNaak1BMEcKQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUJJRmdKKzNEbFZ4bE1zSXBqZEZjbUtMeVltYTl3RUg5cDQ4T0hyWVE5YwpVWXMzaWNxWGpiMm0yakt6QitSbDMySUxYNENIMFplM1ZoaDZSVFJUbVFyNTREQ3VzTEpZOUJkWnh5UFNkNWRqClVORkFTbTBSa2xZdDN5UjhDYU41M0tSbHp5SjNlRVdNZm1HZWVMbmI1aU9wTU1tWi9ic0h1UTN5dlhYMnRsY2kKRmFLQVNQdE1wVXpFTUljb3hXV3hrUXR4YXF4SlFSazlwQktlQ1BYQVVJNFdxbW83U1hGanB2QkxJdlZCOWRGTApYZnhEUFFWRU8rRGZlT3hNWXZscTVNVUVodWczTmxtZU9FcVgybk1KTWxFU0Q1cy9IY2ZSVm1iQWR0L0ZtbE5WCkxqWmhGNG5TZVJvQnpCdDlsc1gyckFFWGdzWEhUSXM3NGFXaGtjTFpxTXdWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBejYzZURZT0hLZm9WTGM4c1ZSSEI0YUVKcEp5bEozUnA5UmI5b04yU2lxZVozV0RrCmtXVzY3ZzFJczJFL3NuVkpjc1N0azBvVmExTEhMWjZuUFk0ZndHMEpwT2FFNjRKcnNpUkYweFM4YXFhSm93OUwKeE9HRXNNMkJyanZtNjhYQlU3WmRza3NBYzBsdVROQURxRW5GRmdidEVBRFVWb3BSWldzSXBrOEpmT01hRWRoOQpUbk1lVVZsbjB4N1pEZVE0ajFOMmFKdEIwaXYzbGpKQk5JT2cxWUxOSm9XQTBZQ2VScnNLK2Zlb3JaNDJxaTZ4CjJWVDRVdHNEOURaYWI3Rlk3OTVVYllJbmVjbUdHRzdvK09BMWU0dCtWUEpyMFJtOVlaekU1c2ppZFlxSTNaRUUKNTcxbEdycG9rZHFKRy9XRGNqT3RjcTBmK04rOFl1UzVrT1ljT1FJREFRQUJBb0lCQUNITmIrWU5NWFBRbzUvWQpKNlFWQnRTZHJIOGhpL1FYQzZQN3dQNXM4Z3dsYVhMUjhZSUU1OThWUkc4RjlpTXEyZkNYT0pWUHFwclVWMTBDCmhNQU5JUGZtQjNyU2xuSHF3WEsyV3JNWG5lOVIrZmNUWjBhOVdpYVkzSEdxaUZSNTFKUzJpeHVZLzVMRU1mTEkKckwrNGVoNnlzK1UxN1ZuRW02a0JPZUF2M3lCM1gweTJaa08wanQ3ZHh6VVMyTFEzSnpkbk5qMDJCUHd2QnVJYQpSTTlWVEFOaUNjN1hiY24wRGNPS29NbDZVVVNaV0NKTjZiS3lna1IvWGpEcG9PcEFoMWs4N3lzVmV5L1BwSzRSClp1czMzWFdjVjRQdE1RbEUrQ1FzdHNUN3VFREN5MndIMCt4cm1wZWFCaWhYUjhLMm1QVEJrR25FVmtXc3hGTlQKWE02VDBYMENnWUVBN3M1eFNKOEZGeWdJWHNEbktvQXZzSVJnTkcwWVRGY1dBRXJQWWpMTm9UTnZIL0p4ZGIycAorUTBLMXd4QkQ4WXkzVjNrTUdreUQ2VzhYbUhZSGttMXdQYkxUT2xkSGlJVjVoK3lQV2hiNlF2V1RLQitISWYzCi9YNlJ2b3JrSzJOTzNWV0dWR0tBRXMxQktpdFZmVE1yT0g4bDBVV2ZyUUxrcUJ1Smc0aGdsUDhDZ1lFQTNxRzAKRTNHY3F5K2pBOTNyL2xsOGU1a0tIUlhoYWszbEdoY2N1VEdEenMxazd2Ylp1K1VSVkpMV0NySUFLVHpMUVpoZQpGc1ZPQXl2WU1VUEFPbUFUQnNoNEZKaG9rRnI0T2hvTHhhTUdnSk5IaWQ4bjhlcmkrMDQ2S1NRaHBMK045WVo1CnpxSXhxRlhETnhpUFJJdzNiT0E1NnlybUNwWjhvSTFZZU5NYnRzY0NnWUJ5dGpZU2xWaURwQlpKTmM2VlN0Z2QKcWFqdzVncksrUFkzazdnRXlyU2VINi9jbjhCQ3Q2WERYYkY4VllXWFJ6Uzl3MUZPcytsNVBMcThkN0d4OHVSYwoyZkFVZFBEbS9hYVpVVlowU3dJRGMwMHdwOU9NYndBQUErR01ydmtsb21HS3puOWxYNTkzNktMSjErRUw4QjF0CjJSM1laZUpxNEQzb1Jyb0t0ZUwzRHdLQmdRRFZhS0JidXg1NUlsTGJWQkh5WVFsbzJVek9rTGpoMUFWM093eDMKb2JVOXVibTFMNytMMDRzSFRUSU1VcERBOXR2SDV5emFHd3dyRWc1Tk95cTdTbmt5bVZ3eU1kNlo4Zm5jaURjYwpucWVPL0o4bzFGZFFHTjY0RTBiQlJUZFMyNlJTNVROQ0Zrd1BseFpvYkF4NW93ZEdRTEtFY1R6T2pXNnQ0SkFjClVoRlE1UUtCZ0JFMXNuMUpGOTlZN1ZFK1c0VVdoVXErTzVwTUVQSFNZR253VGlEZ2pURlU1ZDRSQVpTcmo2SFgKUGxzYmVSMFZ6aGpNLy85SGQ4R1BlOHl2b0c2N05wMUowbC81UDVxMFBpc0NGNlJhdjBlRlBGNTltQzFhZC9MVQpCN3ZvUERlOFRVMkFiRjYveUJoR3JJci93cmNsTG1kYklhSUo4OXhLNTkyMGJtazFXcGNhCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: default
type: Opaque
