##################################################
## Gateway Service
##################################################

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  ports:
    - name: http
      port: 5000
      targetPort: gateway-port
    - name: https
      port: 443
      targetPort: webhook-port
    # - name: admin
    #   port: 8080
    #   targetPort: admin-port
  selector:
    app: gateway
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env-configmap
  namespace: default
data:
  APP_ENV: "development"
  ADDRESS: ":5000"

  WEBHOOK_ADDRESS: ":8443"
  WEBHOOK_KEY_DIR: "/run/secrets/tls/tls.key"
  WEBHOOK_CERT_DIR: "/run/secrets/tls/tls.crt"

  ACCOUNTS_DISABLE: "true"
  ACCOUNTS_ADDRESS: "api-accounts-v1-accountsservice.default.svc.cluster.local:5000"
  ACCOUNTS_TIMEOUT: "10"

  DISABLE_K8S_CLIENT: "false"
  ENABLE_STACKDRIVER: "false"

  PROTO_MAP: "proto/map.json"

  # Redis
  REDIS_ADDR: 'redis-gateway.redis-gateway-service:6379'

---
# Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: api-gateway
      containers:
        - name: gateway
          image: registry.gitlab.com/eco_system/gateway
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway-port
              containerPort: 5000
            - name: webhook-port
              containerPort: 8443
            # - name: admin-port
            #   containerPort: 8080

          envFrom:
            - configMapRef:
                name: gateway-env-configmap
#            - secretRef:
#                name: gateway-env-secrets
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true

          livenessProbe:
            httpGet:
              path: /hz
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 120

      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls

      imagePullSecrets:
        - name: gitlab-auth

---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: default
---
# Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: api-gateway
rules:
  - apiGroups: ['', 'extensions', 'apps']
    resources: ['services', 'namespaces']
    verbs: ['get', 'list']

---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: api-gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-gateway
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: default

---
##################################################
## Gateway Webhook
##################################################

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gateway-webhook
  namespace: default
webhooks:
  - name: gateway-service.default.svc
    clientConfig:
      service:
        name: gateway-service
        namespace: default
        path: '/admission'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lVS2xpc1pBZHpVR2FvU3NuQjlUcVdTNGtTN2xNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUNnd1BaMkYwWlhkaGVTMXpaWEoyYVdObE1CNFhEVEl4TURjeE5UQTBNelUwT1ZvWApEVE14TURjeE16QTBNelUwT1Zvd0dqRVlNQllHQTFVRUNnd1BaMkYwWlhkaGVTMXpaWEoyYVdObE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZKVFFiMjFvajB4dkMyS1NuMXRvSWh6a3Bld04KcWdtb0RiTEpDNUZKell6VWU0VmdTTDVOekpFRnlHL3NyRk5meVhQcnlPYnVBaXVrc2tGdThwU1VvblllQWNSaQpCY1RsdXpEOTl6Z045aDJQZGxrQ2psWnpYdEY1eEtmT0JKQ3F6OFdwOFFlaDJIOEt6akxBbExhMzVYM0pnemFpCk5OMkUzZ0ptc09pV1R1OFh6akZrajRxb3d0eWV5TVZ3TVIySEFIREppUG11NUVBd0ZQV0prMWlKK2ZOUS9NelAKUy9oLzFIUCtZbnhac1hDcnVvZHBvSzlMQktlcTVFTW1HWEZZV1hZUmtLOFZuSEM5WW9kTlhack14eVp0ZVpvVgpXTHZZM2d2K01VR3VaaVA4R2RuV0ZNRHgyUHkzaU5vZFYxc0VJTEVDUCtVbHAzSUlTUGRNQ3FIYk9RSURBUUFCCm8xTXdVVEFkQmdOVkhRNEVGZ1FVZTc4UGJ1akxrN1lXTzlpZFJCOUpzQmhVaUFrd0h3WURWUjBqQkJnd0ZvQVUKZTc4UGJ1akxrN1lXTzlpZFJCOUpzQmhVaUFrd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFsNnRtd29MaU5pcENQK0dPSGhodzFoTk5LZE4xSllScldURTFObWQ5RWhvNi85WTk4UlJvClcyWThsNTdlQ2RTMG9MYU9xL2pGNkxYTVRhZXE3cyttRENQVFVSdlZYTEJjSG00SWdYd1RaNitMREw5YjB1eGYKMG1DL25kYldFbWtsWkxtc0hRNzMzYm9VWmlYS0ZaSmFlZklnYnYrWUprTXNmdGdUdkRHeUs5SGtaVG91bThnNwpJSkp5UE5ZUjVmUllZU25HZ2JRbzVQb2c0NnJGZGxyUDdTQm9EVzUzbTc0UWVhNjduajFqK25IVTMzVURLcU5DCitmZFU0aWl5M1hMY1h4QjV6SnVYRE9iQmdTZVBZMWNKdVdyQU5OTTRieFdqWVJZM0w4MDZWVWxOYmloSEJxWVYKclZuWDFaT0dhTjJEeGdLWHFJNkFvVWVnMmZ4T01EYTFuQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ['*']
        apiGroups: ['*']
        apiVersions: ['*']
        resources: ['services']
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lVS2xpc1pBZHpVR2FvU3NuQjlUcVdTNGtTN2xNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUNnd1BaMkYwWlhkaGVTMXpaWEoyYVdObE1CNFhEVEl4TURjeE5UQTBNelUwT1ZvWApEVE14TURjeE16QTBNelUwT1Zvd0dqRVlNQllHQTFVRUNnd1BaMkYwWlhkaGVTMXpaWEoyYVdObE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZKVFFiMjFvajB4dkMyS1NuMXRvSWh6a3Bld04KcWdtb0RiTEpDNUZKell6VWU0VmdTTDVOekpFRnlHL3NyRk5meVhQcnlPYnVBaXVrc2tGdThwU1VvblllQWNSaQpCY1RsdXpEOTl6Z045aDJQZGxrQ2psWnpYdEY1eEtmT0JKQ3F6OFdwOFFlaDJIOEt6akxBbExhMzVYM0pnemFpCk5OMkUzZ0ptc09pV1R1OFh6akZrajRxb3d0eWV5TVZ3TVIySEFIREppUG11NUVBd0ZQV0prMWlKK2ZOUS9NelAKUy9oLzFIUCtZbnhac1hDcnVvZHBvSzlMQktlcTVFTW1HWEZZV1hZUmtLOFZuSEM5WW9kTlhack14eVp0ZVpvVgpXTHZZM2d2K01VR3VaaVA4R2RuV0ZNRHgyUHkzaU5vZFYxc0VJTEVDUCtVbHAzSUlTUGRNQ3FIYk9RSURBUUFCCm8xTXdVVEFkQmdOVkhRNEVGZ1FVZTc4UGJ1akxrN1lXTzlpZFJCOUpzQmhVaUFrd0h3WURWUjBqQkJnd0ZvQVUKZTc4UGJ1akxrN1lXTzlpZFJCOUpzQmhVaUFrd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFsNnRtd29MaU5pcENQK0dPSGhodzFoTk5LZE4xSllScldURTFObWQ5RWhvNi85WTk4UlJvClcyWThsNTdlQ2RTMG9MYU9xL2pGNkxYTVRhZXE3cyttRENQVFVSdlZYTEJjSG00SWdYd1RaNitMREw5YjB1eGYKMG1DL25kYldFbWtsWkxtc0hRNzMzYm9VWmlYS0ZaSmFlZklnYnYrWUprTXNmdGdUdkRHeUs5SGtaVG91bThnNwpJSkp5UE5ZUjVmUllZU25HZ2JRbzVQb2c0NnJGZGxyUDdTQm9EVzUzbTc0UWVhNjduajFqK25IVTMzVURLcU5DCitmZFU0aWl5M1hMY1h4QjV6SnVYRE9iQmdTZVBZMWNKdVdyQU5OTTRieFdqWVJZM0w4MDZWVWxOYmloSEJxWVYKclZuWDFaT0dhTjJEeGdLWHFJNkFvVWVnMmZ4T01EYTFuQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lVV3FpWXpBS2xzaHhvOWQrc0M5aFpZRG8vK1pjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUNnd1BaMkYwWlhkaGVTMXpaWEoyYVdObE1CNFhEVEl4TURjeE5UQTBNelUwT1ZvWApEVEl4TURneE5EQTBNelUwT1Zvd0pqRWtNQ0lHQTFVRUF3d2JaMkYwWlhkaGVTMXpaWEoyYVdObExtUmxabUYxCmJIUXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyVEFJS1g4bHlCZy8KY3NCd1NXRUVZRlJ5amZOb25zVDRDTXVxZExNNHpCS1M0K1MyZzBZWHhHdkRGbDBPVWhocEVSQU1xZVN5THh1cQo5enBqcnQ0NFpmVFZiMDV4UVR2dmFtYkJrRHcvOTN1d0ZhRGhLYXpFSnB0ZEU2cWxHaG5yODJKcWJJcVg1Q0xFCkgrN0lSR1RoK0F3Q0NWMkJSaWpCREROUCtqcEZTSXFzQ0lpQjZrRFhKNTJVN25ya2JNRW1lY1JadFoyYldZN1EKekdIU0tjbHovcW4rZ0tjSFFtS0xDaHRxVTI0MmdEVFQ5ckc3ek5aakhLM0FlTTB2MlZZOTljSHJTdlo1dFYxNwppekFMZDg3Tk9Fc01ic2lpRVV1d3Y5R0R3enJvQkdrRkNkcEhMYVU4WEdUZm9kVzRIOW1hSlE3K2lyaEhvaFJFCkpwQWxCeUh4UFFJREFRQUJveW93S0RBbUJnTlZIUkVFSHpBZGdodG5ZWFJsZDJGNUxYTmxjblpwWTJVdVpHVm0KWVhWc2RDNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURZR1RxZmNIK3NzMWEwb28yR283WDJJSkFFNwpmRVpZbVpUK1o4UFhIcStZYW9uSzR3M2NMSUEvZk1FTTdTN09TbGp2Y3d3aDZDMFNjMUdsUk4yUmZDZFdXcWdOCnI5QXhvdmNHZmdjUDhJa2FyblFiU01RVTJwRk1nUkt3ZFFHcnlDOFlNdlVNOFlrL1EzY2RSZWZGRXJvKzVEK3IKd2pPeGV6czl6eVRrQTB1ZGVsdXhVTytKb0xoMkVMbVY3bC9Sc210dTNFY1gwdXh1b2k5TXFsLzlTUFZzSlRmSQorMFBQQU0vbkl4REliWmNmaWpwd2UyeTFDS2k4Z0V1c1B0NU45RzhxcjUyTEFranUvWWxsRnpRZkZHZUhIU0NKCmI5RHl6dHF6M2MzanBRZDNrWDgyL1RKR0szcU9FZmVHMnRvT3dGRy9mdlJZWEJvYm9DdGpvZ3hScDQwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBclRBSUtYOGx5QmcvY3NCd1NXRUVZRlJ5amZOb25zVDRDTXVxZExNNHpCS1M0K1MyCmcwWVh4R3ZERmwwT1VoaHBFUkFNcWVTeUx4dXE5enBqcnQ0NFpmVFZiMDV4UVR2dmFtYkJrRHcvOTN1d0ZhRGgKS2F6RUpwdGRFNnFsR2hucjgySnFiSXFYNUNMRUgrN0lSR1RoK0F3Q0NWMkJSaWpCREROUCtqcEZTSXFzQ0lpQgo2a0RYSjUyVTducmtiTUVtZWNSWnRaMmJXWTdRekdIU0tjbHovcW4rZ0tjSFFtS0xDaHRxVTI0MmdEVFQ5ckc3CnpOWmpISzNBZU0wdjJWWTk5Y0hyU3ZaNXRWMTdpekFMZDg3Tk9Fc01ic2lpRVV1d3Y5R0R3enJvQkdrRkNkcEgKTGFVOFhHVGZvZFc0SDltYUpRNytpcmhIb2hSRUpwQWxCeUh4UFFJREFRQUJBb0lCQUJPUzNTbExmSXFyNnVmZQpSaEtWQzNpVHNzckdXdW11MjFXckp4Mi9iOGpveEg5TFJ6RjVCNUNrbVV6NndYYVgyYkFhLzBOb1hKY2thbU04Cnp5MWhZa0JydG4rNC91WGZqMFNZVG9JdHZSRU1ncTgvR3BPcU9oVWU5QnNYNjBjUzdPNzZEWXNzOHRQTzlobWgKMURLZXNFZG5uQWRROFI1cjFyMjVRdTNHRGpTUGdCSUpjN3JTd0FVZEp1WmoyS3VTSTYrU3J2Z09VY0hGR0pLRwppRmJrU0kwaXdhS2wzMTFvQXllTXNXT3h4eFdJZjZqcVRrVDRmTnRTbnlMNldUaC8xTTFaM0d2RDFhaHRTSDRJCmRBcG9IN0k5bm13a1JWTUduQ1pnTTQ4b05GaFlpeHJyZE1jMWg0NHA2Z2U0cTZZN1NGZVNTRkNNemRvK0xpRFcKZVZzS3ZDRUNnWUVBM0syUDJhV2dJUUxvZlBvMXQya0dRVzNWUVBCdnRsMkZXb0E0SjVWNXBZWFgrcXUvSnBLdgpiRnpaMUNoam1jWWJrZTR6bHNsZnpLajhvcUxqalhOZkdpR2E1Q1RqemM1dC8wWnJ2UGNkaVRrbUROY01PdEhWCmJhenNqa0tKd2lJVVJ6M1RkYnRraHBOUE05eWFuUU9WTlV5aTlIcUZJTHFveDRaNlM3bVJPTGtDZ1lFQXlPaUUKMEZteHB2bTAyZVdYRmVEVVFSaExXN25EamRENldNS2FUdWdSZWVKdVQ5RytPdXIxMXVnbnF0S2dWNDdPbVBvRApNNWJQRzFCOXhyZ0l6V1lJWUR5VFdsRk5FUVZyenJBVldnMGNuSDlCTFpGOXFFaDhJYWNuSE5zM3Y4M0ZRbVVkCnorL293aG1oMk91K1FXaU1NWmhiZEJyZ0ZmZVBKRkd0bW54MmNxVUNnWUJ2N0Z0VUlPdXBNb2RsczZXQTQzUjMKeE5QdS9zTTU5QTdKaXRSd1J5Q09jZWJMelVYQ3M0empZZWhjOFNzcTk4NU40a2txQmZKZm82bVdkeFVBVGU2RApHMTRxcmdjWC84WE1QaFF3b0FqTDZ6OUFMZVdYQTR2QzkzeDIzb3B0K3NqY0pTQlZ5dmcrUlFKYnBGeUtuQ0dXCkNjdHdRWis1ck5JamVESVlyQUphaVFLQmdFZm5KN2xsa0hZaEFqL0Zzb2ZxK2l2OTVPS0VIbCsvL2drTVJLdWUKMUxwWmRuOXNvbmQxcGR4dkk5czRISmlaaklrbFdVWDZZRTczUkx4OUd2RmY1Zm1EVkgxTGdaaG81MGVHcjIyVwpLYm84dFBmNURRN1FPbFRVL09PUDlXalkzUk5CR3lWVFNHdEhQeXhpV3FvUUg3U1VRWTdSRzRmaEhNS3oxTHpvCmRIL2RBb0dBYXc0RGorb1hjL0JOWVNwUzJtajZGbjdCMFJnSEgvWUF2QUVQZzRsVTNJMzVRMkl6ZFl6QmZBNnMKUkRVL1NUWkJLdW1rY0xBd3JTKyt6OGw5ZW9TT3R4UEwvVjBYUzZldnFCcEk3VERPOHQ5RjArUGJ1RjVpMWliLwo4TGRIV1krNEo4a1pienQ2RC92a21UN1lnQXhWS0xlallIVDVsTTh6eURhemhoWS9vRWs9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: default
type: Opaque
