package internal

const ProtoTemplate = `
// Code generated by hack/genproto. DO NOT EDIT.
package server

import (
	{{- range $i, $e := .}}
	"github.com/isaiahwong/gateway-go/proto-gen{{ $e.Path }}"
	{{- end}}
)

var _Services = map[string]ServiceDesc{
	{{- range $i, $e := .}}
	"{{ $e.Package }}.{{ $e.ServiceName}}": ServiceDesc{
		ServiceName: "{{ $e.ServiceName }}",
		PackageSVC: "{{ $e.PackageSVC }} ",
		Package:        "{{ $e.Package }}",
		CurrentPackage: "{{ $e.CurrentPackage }}",
		Handler: {{ $e.CurrentPackage }}.Register{{ $e.ServiceName }}Handler,
	},
	{{- end}}
}

// Returns generated protos that have been generated with  protoc-gen-grpc-gateway
func GetProtos() map[string]ServiceDesc {
	return _Services
}
`
