package internal

const ProtoTemplate = `
// Code generated by gitlab.com/eco_system/gateway/hack/genproto. DO NOT EDIT.
package api

import (
	"context"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	{{- range $i, $e := .}}
	"gitlab.com/eco_system/gateway/api/go/gen{{ $e.Path }}"
	{{- end}}
)

type ServiceDesc struct {
	ServiceName    string
	PackageSVC     string
	Package        string
	CurrentPackage string
	Handler        func(context.Context, *runtime.ServeMux, *grpc.ClientConn) error
}

var _Services = map[string]ServiceDesc{
	{{- range $i, $e := .}}
	"{{ $e.Package }}.{{ $e.ServiceName}}": ServiceDesc{
		ServiceName: "{{ $e.ServiceName }}",
		PackageSVC: "{{ $e.PackageSVC }}",
		Package:        "{{ $e.Package }}",
		CurrentPackage: "{{ $e.CurrentPackage }}",
		Handler: {{ $e.CurrentPackage }}.Register{{ $e.ServiceName }}Handler,
	},
	{{- end}}
}

// Returns generated protos that have been generated with  protoc-gen-grpc-gateway
func GetProtos() map[string]ServiceDesc {
	return _Services
}
`
