##################################################
## Gateway Service
##################################################

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  ports:
    - name: http
      port: 5000
      targetPort: gateway-port
    - name: https
      port: 443
      targetPort: webhook-port
    # - name: admin
    #   port: 8080
    #   targetPort: admin-port
  selector:
    app: gateway
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env-configmap
  namespace: default
data:
  APP_ENV: 'production'
  PORT: '5000'

  WEBHOOK_PORT: '8443'

  GIN_MODE: 'release'

  DISABLE_K8S_CLIENT: 'false'
  ENABLE_STACKDRIVER: 'false'

---
# Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: api-gateway
      containers:
        - name: gateway
          image: registry.gitlab.com/isaiahwong/cluster/gateway
          imagePullPolicy: Always
          ports:
            - name: gateway-port
              containerPort: 5000
            - name: webhook-port
              containerPort: 8443
            # - name: admin-port
            #   containerPort: 8080

          envFrom:
            - configMapRef:
                name: gateway-env-configmap

          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true

          livenessProbe:
            httpGet:
              path: /hz
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 120

      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls

      imagePullSecrets:
        - name: gitlab-auth

---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: default
---
# Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: api-gateway
rules:
  - apiGroups: ['', 'extensions', 'apps']
    resources: ['services', 'namespaces']
    verbs: ['get', 'list']

---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: default
  name: api-gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-gateway
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: default

---
##################################################
## Gateway Webhook
##################################################

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: gateway-webhook
  namespace: default
webhooks:
  - name: gateway-service.default.svc
    clientConfig:
      service:
        name: gateway-service
        namespace: default
        path: '/admission'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzRENDQVpnQ0NRRG5Ya1VKbU05V0RqQU5CZ2txaGtpRzl3MEJBUXNGQURBYU1SZ3dGZ1lEVlFRS0RBOW4KWVhSbGQyRjVMWE5sY25acFkyVXdIaGNOTWpBd01qRXdNVE0xTmpNd1doY05NekF3TWpBM01UTTFOak13V2pBYQpNUmd3RmdZRFZRUUtEQTluWVhSbGQyRjVMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRDd0aGk2U1hiWWdxZk84Y09FT1o3azF2emNJNmx6dkU3MVNzdWpyM0dwS0lqOFhKTzcKTHh6aFd4NkdvWlVMYXd1bTgwQlFnRm54RHkzUEd2YU44OGFHZUM0V1ZOeWVsdHR5TUh5L1lISkZxcnQ3d3Y5QgpjNlJhcU1TM2JjVzVTU3JzbWMwbVI3MjYyaGZ0ZHVHMkZlMVFXbEoyWEF0SWdCMnoxOFdERi9YMDdEalhYRGZvCjhWQXdOK2JuQ1UyYjgwL0N5RzA1Q0ZqZEtGbzJmM1JBR3VZWFpTNDVvZUlObFNkWTMvNmgxYWtoRUJROHVCbTcKSmw1U3k3SklPejlBTFpSOWh6aWpVL25PVG05anFyMVZlMVdqZ09QZHZraEVONUt4cEZnakJlSVNrcy9HTHI2aApTSytneUpZbjlHTDNWcloyazd2Y2dONGlyUkdrZUlZMC93WmJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBQjIrUnhlbjAwY1c1bVdjRmJacTJyV05DQzRXb21pQmFNcGZzTDNJYTI2RnhrREZMSHQ4eUw5TXF5ZlUKRHhHTlFUZ1lSa3RERzlFUXhFWHhWc0NzOXliRXBYUnM1YVhLQ1BST3RUbTBKd0xlUEhhN1BHTW42K2ZLTmlNSgpneU9xcDE1RFlGS1VFdVdWQWhSb3NZR24wNDlDZXZzV2paZlc3eXRteFM1dkcyTWgwNjlzTGdxVDZqSmN5T0I3CkhvcnB1ZXV3UlpCdEFHTGdTcVVta3lsQWY2QkIvcTlRVVVyN1J3bkgva01YZEhrU092WmxjbmVzYVFlcW9SNSsKdDlEMG9qR2llMXJZZFVaT0pQb1Nnek5oK0lRVXQxSjl2Z2JHQXFoNUd6K2wxZWJrMXp5bGZINEFHd0JaR3kyYgo5V2lzM1BpbDdjUDZPY0FtQXlqbjEwRDRaZWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ['*']
        apiGroups: ['*']
        apiVersions: ['*']
        resources: ['services']

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzRENDQVpnQ0NRRG5Ya1VKbU05V0RqQU5CZ2txaGtpRzl3MEJBUXNGQURBYU1SZ3dGZ1lEVlFRS0RBOW4KWVhSbGQyRjVMWE5sY25acFkyVXdIaGNOTWpBd01qRXdNVE0xTmpNd1doY05NekF3TWpBM01UTTFOak13V2pBYQpNUmd3RmdZRFZRUUtEQTluWVhSbGQyRjVMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRDd0aGk2U1hiWWdxZk84Y09FT1o3azF2emNJNmx6dkU3MVNzdWpyM0dwS0lqOFhKTzcKTHh6aFd4NkdvWlVMYXd1bTgwQlFnRm54RHkzUEd2YU44OGFHZUM0V1ZOeWVsdHR5TUh5L1lISkZxcnQ3d3Y5QgpjNlJhcU1TM2JjVzVTU3JzbWMwbVI3MjYyaGZ0ZHVHMkZlMVFXbEoyWEF0SWdCMnoxOFdERi9YMDdEalhYRGZvCjhWQXdOK2JuQ1UyYjgwL0N5RzA1Q0ZqZEtGbzJmM1JBR3VZWFpTNDVvZUlObFNkWTMvNmgxYWtoRUJROHVCbTcKSmw1U3k3SklPejlBTFpSOWh6aWpVL25PVG05anFyMVZlMVdqZ09QZHZraEVONUt4cEZnakJlSVNrcy9HTHI2aApTSytneUpZbjlHTDNWcloyazd2Y2dONGlyUkdrZUlZMC93WmJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBQjIrUnhlbjAwY1c1bVdjRmJacTJyV05DQzRXb21pQmFNcGZzTDNJYTI2RnhrREZMSHQ4eUw5TXF5ZlUKRHhHTlFUZ1lSa3RERzlFUXhFWHhWc0NzOXliRXBYUnM1YVhLQ1BST3RUbTBKd0xlUEhhN1BHTW42K2ZLTmlNSgpneU9xcDE1RFlGS1VFdVdWQWhSb3NZR24wNDlDZXZzV2paZlc3eXRteFM1dkcyTWgwNjlzTGdxVDZqSmN5T0I3CkhvcnB1ZXV3UlpCdEFHTGdTcVVta3lsQWY2QkIvcTlRVVVyN1J3bkgva01YZEhrU092WmxjbmVzYVFlcW9SNSsKdDlEMG9qR2llMXJZZFVaT0pQb1Nnek5oK0lRVXQxSjl2Z2JHQXFoNUd6K2wxZWJrMXp5bGZINEFHd0JaR3kyYgo5V2lzM1BpbDdjUDZPY0FtQXlqbjEwRDRaZWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2RENDQWFRQ0NRQ3NETnJBL1YxRkhUQU5CZ2txaGtpRzl3MEJBUVVGQURBYU1SZ3dGZ1lEVlFRS0RBOW4KWVhSbGQyRjVMWE5sY25acFkyVXdIaGNOTWpBd01qRXdNVE0xTmpNd1doY05NakF3TXpFeE1UTTFOak13V2pBbQpNU1F3SWdZRFZRUUREQnRuWVhSbGQyRjVMWE5sY25acFkyVXVaR1ZtWVhWc2RDNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURtMjZtd1VkTTVVMlRYYjVKQTJwenQwVWpxMjZhbGRsbHoKWjE5M1g4KzBqcFZkY0VqZ3JRVGxTZmNSRHJxUHJCay9vUnVtZ3JQaCtoZ2U0S3Q1d1VFeGtOZzU3ZHNYMlhKZgozbXBYWFp0cFBaN1poYXoxMWtMQmEyOUtobU5TczJ1R2xxR0NlYzQyTzdvZmo2VnlaTWp6T1VSclQvSXJJdnhFCnYveXcrTmtTb1dIeUtudFNhZ1l6K3ZLQUozbFphcjAvK3J0bmFLc2Y0bVV3cnpSVHQvUFNhU2RZL0d4RDY5L1UKOTVkS1pEZHU3QXVGVm81TzN6S0drZlc5YmRySzYyRStJRWpnT2ZrMXRVZCtUczRUYm5MT1dtQk5talp0OUpaZAo4cVFXcWs2T05saUE0NC9LV0VRNU01bWtUVmtaY2tmMGo5dW14d3Flejg5Z3FDdzVNang1QWdNQkFBRXdEUVlKCktvWklodmNOQVFFRkJRQURnZ0VCQUFKUVZMS3NRSUI4S3pCME5XQ2pMZ0dHT25VV3dyRHZYLzU3a1dLSHNKL04KMUlhSG9jQ1J1NitSaXUzTEtkcGpnMjVoTHpPNC9pNkVzaG4zRE9TWXh1NTgxYmdqNjhjS3dGSDdmVDVkbDFZNAptaFFobUVseHZ4K01PbU9HSXh3SStqbis2SEg4R294MnVyYjMwOTZFdCtjRmVSYmQzN3BqSTVSeWtjU0ttK1NwClBIOGhBR0dXdWpVaEltOGlYblNPQzljL3ZiTEkySUY2NTQyc09MSUhoQXpkQ2FRU0pNZW1Kb0FiVzh2ZGp2U3AKL2ZHVHBnQlF6VTJuVkhvK3hROCthUks5RCtWQnREbVBUNHQrSkp4TnJ4QnZMY3ovR01jTmFjZVl0S2J3M2NJMAp0Y010MFhHZHVFSFo1c29sbXdCVHR2KzA5WWp3a2NZS09ETUJheWhlZXpzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNXR1cHNGSFRPVk5rMTIrU1FOcWM3ZEZJNnR1bXBYWlpjMmRmZDEvUHRJNlZYWEJJCjRLMEU1VW4zRVE2Nmo2d1pQNkVicG9LejRmb1lIdUNyZWNGQk1aRFlPZTNiRjlseVg5NXFWMTJiYVQyZTJZV3MKOWRaQ3dXdHZTb1pqVXJOcmhwYWhnbm5PTmp1Nkg0K2xjbVRJOHpsRWEwL3lLeUw4UkwvOHNQalpFcUZoOGlwNwpVbW9HTS9yeWdDZDVXV3E5UC9xN1oyaXJIK0psTUs4MFU3ZnowbWtuV1B4c1ErdmYxUGVYU21RM2J1d0xoVmFPClR0OHlocEgxdlczYXl1dGhQaUJJNERuNU5iVkhmazdPRTI1eXpscGdUWm8yYmZTV1hmS2tGcXBPampaWWdPT1AKeWxoRU9UT1pwRTFaR1hKSDlJL2Jwc2NLbnMvUFlLZ3NPVEk4ZVFJREFRQUJBb0lCQVFDZStnZ0o1dDlKYTlkVwowSHRyODkvN21aTFlRUGlxbXl5UVgxQ0x1VXdrcjhmR044dklCUDRKRS8xekhxeDB3ZlFGTUdJRk1aN0VjR0JwCjZ4ZksyYjJXYjRPbnFOZW12ZFNZbG1hdTBVUnpuYjZsVnZ1N3M1ZjI4SkFNUnkxZ3h6TzExRWRXdmFDM0VqeGkKL1ozV2YvY3VIM0t4WDdXSjVTYktCVmZ6V3ZySmExQktQcHhuQUlia3VMSk9hZ3dVdEFBdjVrMGg3TUhhdGJkdwprQXRsYzdrWDByY1EwZXVXYmdVMkNDUWxOZDhsZ2J4Z1NuQStDQVd1NjZRVWRCQ2VhMFdyM05oUERXLzZBRHArClowK1M5cFJLL0ZGaTNHMjZFaTFkWjJpRGN1OThoUnhDRC9FTVFjcHpBOTBlc2tRRi9zcUJydERSWWtXaEVWUUYKdmwvQk53ZjlBb0dCQVBpY0tiTGlMYytkMXN2cTU5UDRuRGRtekprTllweVpwY2hjRXVQdHJONlE5ckk1Y2ZTaApycHVKdk9YVHhDOFEyUWIzdmtXekRxem16Ukd1QUovMGRPMzNYMjljYmZzbWJtZWl5Z2FZUlBPVVJtUmRiNHdYCmlkanVsdmt5LzlEK0RWSlpFY2hldVZXWFlGcWhUZWpQMklvVTFOeWV6bmZHVFJCdXpjMEt6a0VYQW9HQkFPMjQKYWVaVzl4V211VkVvd3k0UHBzNDByRURzcXFMazRJc2VxU1VzR3Q4d2EzSjBRM21vSkF5bk9qL3dxLy9XK2RtaApUVDhWQWs5ZVB1TDdZcWFEZ3E5aXdyV1FXMTkybGpBL25WRnJubkZpRUpudUNPOGhHbE51bC9XdUx5eGppeXN6CmF4ZGgvQUFnZUhXQXg5S1RzeW1WZ1c0YlFhM2JEVng0eldFVmMwanZBb0dCQU9SSzJzdkdnTlRYRjBpNEZGeUYKUGtadG90R2xCZm5SNmZlYi9VaktsMlRsNzNQbjVtb0RFb2tIcWF2T2s2ZTRxK0tIRzNWN29LMUxYK0t0U3l1WApXc3l1elRkQXhFbk5sN0taUFRWakhHWWtzYU0yWGRsaVFCWXh1ZmRxU3BtS3dZYnQvYk5tc0lBVmVzaWV1U0ZoCnczSEJBVnI2aFpSZFI2VWdhdUd2MjRqUEFvR0JBS3gyVUE0V0phZ0Zqd2k4WSsyMDJUVmNyV05rejk3aDRhM00KanJZekswT2s0eTdqL2xmeWprVEh4ZERCa0dkSjFYWDRPZ3g3OTNNUlV0cGx1b3BIZXJZM0ZqK1cvVk5pdTA5Qgp0NlpzUjBURytuaFNZeFRwbFNuV1lGU1REQkpPSFpjMzlJZkFSSXpyQWJsdHRvcWxNU1FJSFNCK2tjWEoyQVd3CmRuL3FpZnJ0QW9HQUdqOFBzNThzT2NUYW1KdGFkdVp1S29aYVdTelZZMVpiU1VoYzhMOHR0OVluRHNNcFZVa08KWlo5YkI1SGVMbnJkaFRudWVCSXl2WVYvOE4wcUU1bjhsamxGRGplWFNSV1N1dVNWR3czYmQzNTkrbVhjN1dDeAppTmRSMmgyVFJjMDUrTklTeGRHN0VxQXhhdk41a1hIMk8zT3g1SUVYdHY0VEtJaUxhYmZMc1RBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: default
type: Opaque
