// Code generated by github.com/isaiahwong/gateway-go/hack/genproto. DO NOT EDIT.
package protogen

import (
	"context"

	runtime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/isaiahwong/gateway-go/protogen/auth"
	"github.com/isaiahwong/gateway-go/protogen/payment"
	"google.golang.org/grpc"
)

type ServiceDesc struct {
	ServiceName    string
	PackageSVC     string
	Package        string
	CurrentPackage string
	Handler        func(context.Context, *runtime.ServeMux, *grpc.ClientConn) error
}

var _Services = map[string]ServiceDesc{
	"api.auth.AuthService": ServiceDesc{
		ServiceName:    "AuthService",
		PackageSVC:     "api.auth.AuthService",
		Package:        "api.auth",
		CurrentPackage: "auth",
		Handler:        auth.RegisterAuthServiceHandler,
	},
	"api.payment.PaymentService": ServiceDesc{
		ServiceName:    "PaymentService",
		PackageSVC:     "api.payment.PaymentService",
		Package:        "api.payment",
		CurrentPackage: "payment",
		Handler:        payment.RegisterPaymentServiceHandler,
	},
}

// Returns generated protos that have been generated with  protoc-gen-grpc-gateway
func GetProtos() map[string]ServiceDesc {
	return _Services
}
