// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile/v1/profile.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_38215115a53bbe72, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Body struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_38215115a53bbe72, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateProfileRequest struct {
	AccountId            string                                       `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DisplayName          string                                       `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DateOfBirth          int64                                        `protobuf:"varint,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Biography            string                                       `protobuf:"bytes,4,opt,name=biography,proto3" json:"biography,omitempty"`
	Images               []*CreateProfileRequest_ProfileImagesRequest `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Gender               Gender                                       `protobuf:"varint,8,opt,name=gender,proto3,enum=api.profile.v1.Gender" json:"gender,omitempty"`
	GenderPreference     Gender                                       `protobuf:"varint,9,opt,name=gender_preference,json=genderPreference,proto3,enum=api.profile.v1.Gender" json:"gender_preference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *CreateProfileRequest) Reset()         { *m = CreateProfileRequest{} }
func (m *CreateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProfileRequest) ProtoMessage()    {}
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38215115a53bbe72, []int{2}
}

func (m *CreateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileRequest.Unmarshal(m, b)
}
func (m *CreateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileRequest.Merge(m, src)
}
func (m *CreateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProfileRequest.Size(m)
}
func (m *CreateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileRequest proto.InternalMessageInfo

func (m *CreateProfileRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *CreateProfileRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreateProfileRequest) GetDateOfBirth() int64 {
	if m != nil {
		return m.DateOfBirth
	}
	return 0
}

func (m *CreateProfileRequest) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *CreateProfileRequest) GetImages() []*CreateProfileRequest_ProfileImagesRequest {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *CreateProfileRequest) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

func (m *CreateProfileRequest) GetGenderPreference() Gender {
	if m != nil {
		return m.GenderPreference
	}
	return Gender_MALE
}

type CreateProfileRequest_ProfileImagesRequest struct {
	Encoded              []byte              `protobuf:"bytes,4,opt,name=encoded,proto3" json:"encoded,omitempty"`
	Order                int32               `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	Type                 ImageDescriptorType `protobuf:"varint,6,opt,name=type,proto3,enum=api.profile.v1.ImageDescriptorType" json:"type,omitempty"`
	Metadata             []byte              `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateProfileRequest_ProfileImagesRequest) Reset() {
	*m = CreateProfileRequest_ProfileImagesRequest{}
}
func (m *CreateProfileRequest_ProfileImagesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProfileRequest_ProfileImagesRequest) ProtoMessage()    {}
func (*CreateProfileRequest_ProfileImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38215115a53bbe72, []int{2, 0}
}

func (m *CreateProfileRequest_ProfileImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileRequest_ProfileImagesRequest.Unmarshal(m, b)
}
func (m *CreateProfileRequest_ProfileImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileRequest_ProfileImagesRequest.Marshal(b, m, deterministic)
}
func (m *CreateProfileRequest_ProfileImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileRequest_ProfileImagesRequest.Merge(m, src)
}
func (m *CreateProfileRequest_ProfileImagesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProfileRequest_ProfileImagesRequest.Size(m)
}
func (m *CreateProfileRequest_ProfileImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileRequest_ProfileImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileRequest_ProfileImagesRequest proto.InternalMessageInfo

func (m *CreateProfileRequest_ProfileImagesRequest) GetEncoded() []byte {
	if m != nil {
		return m.Encoded
	}
	return nil
}

func (m *CreateProfileRequest_ProfileImagesRequest) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *CreateProfileRequest_ProfileImagesRequest) GetType() ImageDescriptorType {
	if m != nil {
		return m.Type
	}
	return ImageDescriptorType_DEFAULT
}

func (m *CreateProfileRequest_ProfileImagesRequest) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type RetrieveProfileRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveProfileRequest) Reset()         { *m = RetrieveProfileRequest{} }
func (m *RetrieveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveProfileRequest) ProtoMessage()    {}
func (*RetrieveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38215115a53bbe72, []int{3}
}

func (m *RetrieveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveProfileRequest.Unmarshal(m, b)
}
func (m *RetrieveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveProfileRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveProfileRequest.Merge(m, src)
}
func (m *RetrieveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveProfileRequest.Size(m)
}
func (m *RetrieveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveProfileRequest proto.InternalMessageInfo

func (m *RetrieveProfileRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type ProfileResponse struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string           `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Biography            *Biography       `protobuf:"bytes,3,opt,name=biography,proto3" json:"biography,omitempty"`
	DateOfBirth          int64            `protobuf:"varint,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Images               []*ProfileImages `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38215115a53bbe72, []int{4}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProfileResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProfileResponse) GetBiography() *Biography {
	if m != nil {
		return m.Biography
	}
	return nil
}

func (m *ProfileResponse) GetDateOfBirth() int64 {
	if m != nil {
		return m.DateOfBirth
	}
	return 0
}

func (m *ProfileResponse) GetImages() []*ProfileImages {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "api.profile.v1.Empty")
	proto.RegisterType((*Body)(nil), "api.profile.v1.Body")
	proto.RegisterType((*CreateProfileRequest)(nil), "api.profile.v1.CreateProfileRequest")
	proto.RegisterType((*CreateProfileRequest_ProfileImagesRequest)(nil), "api.profile.v1.CreateProfileRequest.ProfileImagesRequest")
	proto.RegisterType((*RetrieveProfileRequest)(nil), "api.profile.v1.RetrieveProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "api.profile.v1.ProfileResponse")
}

func init() {
	proto.RegisterFile("profile/v1/profile.proto", fileDescriptor_38215115a53bbe72)
}

var fileDescriptor_38215115a53bbe72 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0x7c, 0x34, 0x93, 0x36, 0x85, 0x55, 0x14, 0xdc, 0xa8, 0x51, 0x8d, 0x41, 0x28,
	0xea, 0xc1, 0x51, 0x83, 0x50, 0x44, 0x8f, 0x29, 0x08, 0xf5, 0x02, 0xc5, 0x70, 0xe2, 0x12, 0x6d,
	0xec, 0x49, 0xba, 0x52, 0xe2, 0x5d, 0xd6, 0x9b, 0x48, 0x16, 0x17, 0x84, 0xf8, 0x07, 0x1c, 0xf9,
	0x59, 0x5c, 0xf8, 0x01, 0xfc, 0x10, 0xe4, 0xf5, 0xc6, 0x4a, 0xdc, 0x00, 0xe5, 0xe6, 0x79, 0x7e,
	0xf3, 0xde, 0xec, 0xce, 0xd3, 0x82, 0x2d, 0x24, 0x9f, 0xb2, 0x39, 0xf6, 0x57, 0xe7, 0x7d, 0xf3,
	0xe9, 0x09, 0xc9, 0x15, 0x27, 0x4d, 0x2a, 0x98, 0xb7, 0x86, 0x56, 0xe7, 0x9d, 0x93, 0x19, 0xe7,
	0xb3, 0x39, 0xf6, 0xa9, 0x60, 0x7d, 0x1a, 0x45, 0x5c, 0x51, 0xc5, 0x78, 0x14, 0x67, 0xec, 0x4e,
	0x7b, 0x43, 0x47, 0x25, 0x02, 0x0d, 0xee, 0xd6, 0xa0, 0xf2, 0x72, 0x21, 0x54, 0xe2, 0x3a, 0x50,
	0x1e, 0xf1, 0x30, 0x21, 0x36, 0xd4, 0x04, 0x4d, 0xe6, 0x9c, 0x86, 0xb6, 0xe5, 0x58, 0xbd, 0x03,
	0x7f, 0x5d, 0xba, 0x9f, 0xcb, 0xd0, 0xba, 0x94, 0x48, 0x15, 0x5e, 0x67, 0x5a, 0x3e, 0x7e, 0x5c,
	0x62, 0xac, 0x48, 0x17, 0x80, 0x06, 0x01, 0x5f, 0x46, 0x6a, 0xcc, 0xb2, 0xae, 0xba, 0x5f, 0x37,
	0xc8, 0x55, 0x48, 0x1e, 0xc2, 0x41, 0xc8, 0x62, 0x31, 0xa7, 0xc9, 0x38, 0xa2, 0x0b, 0xb4, 0x4b,
	0x9a, 0xd0, 0x30, 0xd8, 0x6b, 0xba, 0x40, 0xe2, 0xc2, 0x61, 0x48, 0x15, 0x8e, 0xf9, 0x74, 0x3c,
	0x61, 0x52, 0xdd, 0xd8, 0x7b, 0x8e, 0xd5, 0xdb, 0xf3, 0x1b, 0x29, 0xf8, 0x66, 0x3a, 0x4a, 0x21,
	0x72, 0x02, 0xf5, 0x09, 0xe3, 0x33, 0x49, 0xc5, 0x4d, 0x62, 0x97, 0x33, 0x93, 0x1c, 0x20, 0x6f,
	0xa1, 0xca, 0x16, 0x74, 0x86, 0xb1, 0x5d, 0x71, 0xf6, 0x7a, 0x8d, 0xc1, 0x73, 0x6f, 0xfb, 0x7a,
	0xbc, 0x5d, 0x93, 0x7b, 0xa6, 0xbc, 0xd2, 0x9d, 0x06, 0xf4, 0x8d, 0x10, 0xf1, 0xa0, 0x3a, 0xc3,
	0x28, 0x44, 0x69, 0xef, 0x3b, 0x56, 0xaf, 0x39, 0x68, 0x17, 0x25, 0x5f, 0xe9, 0xbf, 0xbe, 0x61,
	0x91, 0x4b, 0xb8, 0x9f, 0x7d, 0x8d, 0x85, 0xc4, 0x29, 0x4a, 0x8c, 0x02, 0xb4, 0xeb, 0x7f, 0x6d,
	0xbd, 0x97, 0x35, 0x5c, 0xe7, 0xfc, 0xce, 0x77, 0x0b, 0x5a, 0xbb, 0xa6, 0x4a, 0xf7, 0x82, 0x51,
	0xc0, 0x43, 0x0c, 0xf5, 0xe1, 0x0f, 0xfc, 0x75, 0x49, 0x5a, 0x50, 0xe1, 0x32, 0x1d, 0xb3, 0xe2,
	0x58, 0xbd, 0x8a, 0x9f, 0x15, 0x64, 0x08, 0xe5, 0x74, 0xcf, 0x76, 0x55, 0x0f, 0xf0, 0xa8, 0x38,
	0x80, 0x16, 0x7f, 0x81, 0x71, 0x20, 0x99, 0x50, 0x5c, 0xbe, 0x4f, 0x04, 0xfa, 0xba, 0x81, 0x74,
	0x60, 0x7f, 0x81, 0x8a, 0x86, 0x54, 0x51, 0xbb, 0xa6, 0x9d, 0xf2, 0xda, 0x1d, 0x42, 0xdb, 0x47,
	0x25, 0x19, 0xae, 0xfe, 0x2f, 0x03, 0xee, 0x4f, 0x0b, 0x8e, 0xf2, 0x8e, 0x58, 0xf0, 0x28, 0x46,
	0xd2, 0x84, 0x52, 0x4e, 0x2d, 0xb1, 0x3b, 0xe5, 0x64, 0xb8, 0x99, 0x81, 0x34, 0x23, 0x8d, 0xc1,
	0x71, 0xf1, 0x64, 0xa3, 0x35, 0x61, 0x33, 0x1e, 0xb7, 0x02, 0x56, 0xbd, 0x1d, 0xb0, 0x67, 0x79,
	0x84, 0x6a, 0x3a, 0x42, 0xdd, 0xa2, 0xf2, 0xf6, 0x5e, 0x0c, 0x79, 0xf0, 0xb5, 0x04, 0x4d, 0xf3,
	0xe7, 0x1d, 0xca, 0x15, 0x0b, 0x90, 0x2c, 0xe1, 0x70, 0x2b, 0x6e, 0xe4, 0xf1, 0x5d, 0xd2, 0xd8,
	0x39, 0xfd, 0x83, 0xe1, 0xfa, 0xc6, 0xdc, 0xee, 0x97, 0x1f, 0xbf, 0xbe, 0x95, 0x1e, 0xb8, 0x64,
	0xe3, 0x35, 0xe8, 0x07, 0x5a, 0xea, 0xc2, 0x3a, 0x23, 0x9f, 0xe0, 0xa8, 0xb0, 0x1d, 0xf2, 0xa4,
	0x28, 0xb9, 0x7b, 0x7d, 0xff, 0xb6, 0x3e, 0xd5, 0xd6, 0xc7, 0x6e, 0x6b, 0xd3, 0x5a, 0x1a, 0xb1,
	0x0b, 0xeb, 0x6c, 0x54, 0xff, 0x50, 0x33, 0xf0, 0xa4, 0xaa, 0x9f, 0x96, 0xa7, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0x83, 0x60, 0xc1, 0xbc, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	RetrieveProfile(ctx context.Context, in *RetrieveProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/api.profile.v1.ProfileService/CreateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) RetrieveProfile(ctx context.Context, in *RetrieveProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/api.profile.v1.ProfileService/RetrieveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	CreateProfile(context.Context, *CreateProfileRequest) (*ProfileResponse, error)
	RetrieveProfile(context.Context, *RetrieveProfileRequest) (*ProfileResponse, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) CreateProfile(ctx context.Context, req *CreateProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (*UnimplementedProfileServiceServer) RetrieveProfile(ctx context.Context, req *RetrieveProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveProfile not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.profile.v1.ProfileService/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_RetrieveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).RetrieveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.profile.v1.ProfileService/RetrieveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).RetrieveProfile(ctx, req.(*RetrieveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.profile.v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _ProfileService_CreateProfile_Handler,
		},
		{
			MethodName: "RetrieveProfile",
			Handler:    _ProfileService_RetrieveProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile/v1/profile.proto",
}
